// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using HCloudAPI.Api;
using HCloudAPI.Model;
using Microsoft.Extensions.DependencyInjection;

namespace HCloudAPI.Clients
{
    /// <summary>
    /// Provides hosting configuration for HCloudAPI
    /// </summary>
    public partial class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new ActionJsonConverter());
            _jsonOptions.Converters.Add(new ActionErrorJsonConverter());
            _jsonOptions.Converters.Add(new ActionListResponseJsonConverter());
            _jsonOptions.Converters.Add(new ActionListResponseWithMetaJsonConverter());
            _jsonOptions.Converters.Add(new ActionNullableJsonConverter());
            _jsonOptions.Converters.Add(new ActionResourcesInnerJsonConverter());
            _jsonOptions.Converters.Add(new ActionResponseJsonConverter());
            _jsonOptions.Converters.Add(new AddLoadBalancerServiceRequestJsonConverter());
            _jsonOptions.Converters.Add(new AddRouteRequestJsonConverter());
            _jsonOptions.Converters.Add(new AddSubnetRequestJsonConverter());
            _jsonOptions.Converters.Add(new AddToPlacementGroupRequestJsonConverter());
            _jsonOptions.Converters.Add(new AddZoneRrsetRecordsRequestJsonConverter());
            _jsonOptions.Converters.Add(new ApplyToResourcesRequestJsonConverter());
            _jsonOptions.Converters.Add(new AttachLoadBalancerToNetworkRequestJsonConverter());
            _jsonOptions.Converters.Add(new AttachServerIsoRequestJsonConverter());
            _jsonOptions.Converters.Add(new AttachToNetworkRequestJsonConverter());
            _jsonOptions.Converters.Add(new AttachVolumeRequestJsonConverter());
            _jsonOptions.Converters.Add(new CertificateJsonConverter());
            _jsonOptions.Converters.Add(new CertificateResponseJsonConverter());
            _jsonOptions.Converters.Add(new CertificateStatusJsonConverter());
            _jsonOptions.Converters.Add(new CertificateStatusErrorJsonConverter());
            _jsonOptions.Converters.Add(new CertificateUsedByInnerJsonConverter());
            _jsonOptions.Converters.Add(new CertificatesResponseJsonConverter());
            _jsonOptions.Converters.Add(new ChangeFloatingIpDnsPtrRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeIPRangeRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeImageProtectionRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeLoadBalancerProtectionRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeProtectionRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeServerAliasIpsRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeServerProtectionRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeServerTypeRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeTypeRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeVolumeProtectionRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeZonePrimaryNameserversRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeZoneProtectionRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeZoneRrsetTtlRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeZoneTtlRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateCertificateRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateCertificateResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateFirewallRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateFirewallResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateFloatingIp201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateImageRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateLoadBalancer201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateLoadBalancerRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateLoadBalancerRequestTargetsInnerJsonConverter());
            _jsonOptions.Converters.Add(new CreateNetwork201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreatePlacementGroupRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreatePlacementGroupResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreatePrimaryIPResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateServerImage201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateServerRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateServerRequestFirewallsInnerJsonConverter());
            _jsonOptions.Converters.Add(new CreateServerRequestPublicNetJsonConverter());
            _jsonOptions.Converters.Add(new CreateServerResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateSshKey201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateSshKeyRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateVolume201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateVolumeRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateZone201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateZoneRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateZoneRequestRrsetsInnerJsonConverter());
            _jsonOptions.Converters.Add(new CreateZoneRrset201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new DeleteLoadBalancerServiceRequestJsonConverter());
            _jsonOptions.Converters.Add(new DeleteRouteRequestJsonConverter());
            _jsonOptions.Converters.Add(new DeleteServerResponseJsonConverter());
            _jsonOptions.Converters.Add(new DeleteSubnetRequestJsonConverter());
            _jsonOptions.Converters.Add(new DeprecationInfoJsonConverter());
            _jsonOptions.Converters.Add(new DetachFromNetworkRequestJsonConverter());
            _jsonOptions.Converters.Add(new DetachLoadBalancerFromNetworkRequestJsonConverter());
            _jsonOptions.Converters.Add(new EnableServerRescue201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new EnableServerRescueRequestJsonConverter());
            _jsonOptions.Converters.Add(new FirewallResourceJsonConverter());
            _jsonOptions.Converters.Add(new FirewallResourceServerJsonConverter());
            _jsonOptions.Converters.Add(new FirewallResponseJsonConverter());
            _jsonOptions.Converters.Add(new FirewallResponse1JsonConverter());
            _jsonOptions.Converters.Add(new FirewallResponseAppliedToInnerJsonConverter());
            _jsonOptions.Converters.Add(new FirewallResponseAppliedToInnerAppliedToResourcesInnerJsonConverter());
            _jsonOptions.Converters.Add(new FirewallResponseAppliedToInnerLabelSelectorJsonConverter());
            _jsonOptions.Converters.Add(new FirewallResponseAppliedToInnerServerJsonConverter());
            _jsonOptions.Converters.Add(new FirewallsResponseJsonConverter());
            _jsonOptions.Converters.Add(new FloatingIPActionsAssignRequestJsonConverter());
            _jsonOptions.Converters.Add(new FloatingIPCreateRequestJsonConverter());
            _jsonOptions.Converters.Add(new FloatingIPCreateRequestHomeLocationJsonConverter());
            _jsonOptions.Converters.Add(new FloatingIPUpdateRequestJsonConverter());
            _jsonOptions.Converters.Add(new GetActions4xxResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetActions4xxResponseErrorJsonConverter());
            _jsonOptions.Converters.Add(new GetActions5xxResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDatacenterResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDatacenterResponseDatacenterJsonConverter());
            _jsonOptions.Converters.Add(new GetDatacenterResponseDatacenterServerTypesJsonConverter());
            _jsonOptions.Converters.Add(new GetFloatingIpResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetIsoResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetLoadBalancerResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetLoadBalancerMetricsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetLoadBalancerMetricsResponseMetricsJsonConverter());
            _jsonOptions.Converters.Add(new GetLoadBalancerMetricsResponseMetricsTimeSeriesValueJsonConverter());
            _jsonOptions.Converters.Add(new GetLoadBalancerTypeResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetLocationResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingFloatingIpJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingFloatingIpPriceMonthlyJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingFloatingIpsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingFloatingIpsInnerPricesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingImageJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingImagePricePerGbMonthJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingLoadBalancerTypesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingPrimaryIpsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingPrimaryIpsInnerPricesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingServerBackupJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingServerTypesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingVolumeJsonConverter());
            _jsonOptions.Converters.Add(new GetPricingResponsePricingVolumePricePerGbMonthJsonConverter());
            _jsonOptions.Converters.Add(new GetServerResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetServerTypeResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetVolumeResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetZoneResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetZoneRrsetResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetZoneZonefileResponseJsonConverter());
            _jsonOptions.Converters.Add(new ImportZoneZonefileRequestJsonConverter());
            _jsonOptions.Converters.Add(new ListDatacentersResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListDatacentersResponseDatacentersInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListDatacentersResponseDatacentersInnerLocationJsonConverter());
            _jsonOptions.Converters.Add(new ListDatacentersResponseDatacentersInnerServerTypesJsonConverter());
            _jsonOptions.Converters.Add(new ListFloatingIpActionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListFloatingIpsResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListFloatingIpsResponseFloatingIpsInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListFloatingIpsResponseFloatingIpsInnerDnsPtrInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListFloatingIpsResponseFloatingIpsInnerHomeLocationJsonConverter());
            _jsonOptions.Converters.Add(new ListFloatingIpsResponseFloatingIpsInnerProtectionJsonConverter());
            _jsonOptions.Converters.Add(new ListImagesResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListImagesResponseImagesInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListImagesResponseImagesInnerCreatedFromJsonConverter());
            _jsonOptions.Converters.Add(new ListIsosResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListIsosResponseIsosInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancerTypesResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancerTypesResponseLoadBalancerTypesInnerJsonConverter());
            _jsonOptions.Converters.Add(new PricesInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancerTypesResponseLoadBalancerTypesInnerPricesInnerPriceHourlyJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancerTypesResponseLoadBalancerTypesInnerPricesInnerPriceMonthlyJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancerTypesResponseLoadBalancerTypesInnerPricesInnerPricePerTbTrafficJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancersResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancersResponseLoadBalancersInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancersResponseLoadBalancersInnerAlgorithmJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancersResponseLoadBalancersInnerPrivateNetInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancersResponseLoadBalancersInnerPublicNetJsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancersResponseLoadBalancersInnerPublicNetIpv4JsonConverter());
            _jsonOptions.Converters.Add(new ListLoadBalancersResponseLoadBalancersInnerPublicNetIpv6JsonConverter());
            _jsonOptions.Converters.Add(new ListLocationsResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListMetaJsonConverter());
            _jsonOptions.Converters.Add(new ListMetaPaginationJsonConverter());
            _jsonOptions.Converters.Add(new ListNetworksResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListNetworksResponseNetworksInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListNetworksResponseNetworksInnerRoutesInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListNetworksResponseNetworksInnerSubnetsInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListServerTypesResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListServerTypesResponseServerTypesInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListServerTypesResponseServerTypesInnerLocationsInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerImageJsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerIsoJsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerLocationJsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerPrivateNetInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerProtectionJsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerPublicNetJsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerPublicNetIpv4JsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerPublicNetIpv6JsonConverter());
            _jsonOptions.Converters.Add(new ListServersResponseServersInnerPublicNetIpv6DnsPtrInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListSshKeysResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListSshKeysResponseSshKeysInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListVolumesResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListVolumesResponseVolumesInnerJsonConverter());
            _jsonOptions.Converters.Add(new ListVolumesResponseVolumesInnerLocationJsonConverter());
            _jsonOptions.Converters.Add(new ListZoneRrsetsResponseJsonConverter());
            _jsonOptions.Converters.Add(new ListZonesResponseJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerAlgorithmJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHTTPJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHTTPConfigJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHTTPProtocolJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHTTPSConfigJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHTTPSProtocolJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHealthCheckJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHealthCheck1JsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHealthCheck1HttpJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHealthCheck2JsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHealthCheck2HttpJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceHealthCheckHttpJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerServiceTCPJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTarget1JsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetHealthStatusInnerJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetIPJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetLabelSelectorJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetServerJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetServer1JsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetTargetJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetTypeIPJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetTypeLabelSelectorJsonConverter());
            _jsonOptions.Converters.Add(new LoadBalancerTargetTypeServerJsonConverter());
            _jsonOptions.Converters.Add(new NetworkCreateRequestJsonConverter());
            _jsonOptions.Converters.Add(new NetworkCreateRequestSubnetsInnerJsonConverter());
            _jsonOptions.Converters.Add(new NetworkUpdateRequestJsonConverter());
            _jsonOptions.Converters.Add(new PlacementGroupJsonConverter());
            _jsonOptions.Converters.Add(new PlacementGroupNullableJsonConverter());
            _jsonOptions.Converters.Add(new PlacementGroupResponseJsonConverter());
            _jsonOptions.Converters.Add(new PlacementGroupsResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryIPJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryIPActionsAssignRequestJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryIPCreateRequestJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryIPCreateRequestLocationJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryIPLocationJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryIPResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryIPUpdateRequestJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryIPsResponseJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryZoneJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryZoneAllOfAuthoritativeNameserversJsonConverter());
            _jsonOptions.Converters.Add(new PrimaryZoneAllOfPrimaryNameserversInnerJsonConverter());
            _jsonOptions.Converters.Add(new RRSetJsonConverter());
            _jsonOptions.Converters.Add(new RRSetProtectionJsonConverter());
            _jsonOptions.Converters.Add(new RebuildServer201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new RebuildServerRequestJsonConverter());
            _jsonOptions.Converters.Add(new RecordJsonConverter());
            _jsonOptions.Converters.Add(new Record1JsonConverter());
            _jsonOptions.Converters.Add(new RemoveFromResourcesRequestJsonConverter());
            _jsonOptions.Converters.Add(new RemoveZoneRrsetRecordsRequestJsonConverter());
            _jsonOptions.Converters.Add(new RequestServerConsole201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new ResetServerPassword201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new ResizeVolumeRequestJsonConverter());
            _jsonOptions.Converters.Add(new RuleJsonConverter());
            _jsonOptions.Converters.Add(new RuleResponseJsonConverter());
            _jsonOptions.Converters.Add(new SecondaryZoneJsonConverter());
            _jsonOptions.Converters.Add(new ServerPublicNetFirewallJsonConverter());
            _jsonOptions.Converters.Add(new ServiceHTTPProtocolJsonConverter());
            _jsonOptions.Converters.Add(new ServiceHTTPSProtocolJsonConverter());
            _jsonOptions.Converters.Add(new ServiceTCPJsonConverter());
            _jsonOptions.Converters.Add(new SetRulesRequestJsonConverter());
            _jsonOptions.Converters.Add(new SetZoneRrsetRecordsRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateCertificateRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateFirewallRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateImageRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateLoadBalancerRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateLoadBalancerServiceJsonConverter());
            _jsonOptions.Converters.Add(new UpdatePlacementGroupRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateServerRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateSshKeyRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateVolumeRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateZoneRrsetRecordsRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateZoneRrsetRequestJsonConverter());
            _jsonOptions.Converters.Add(new ZoneJsonConverter());
            _jsonOptions.Converters.Add(new ZonePrimaryJsonConverter());
            _jsonOptions.Converters.Add(new ZonePrimaryAllOfAuthoritativeNameserversJsonConverter());
            _jsonOptions.Converters.Add(new ZonePrimaryAllOfPrimaryNameserversJsonConverter());
            _jsonOptions.Converters.Add(new ZoneSecondaryJsonConverter());
            _jsonOptions.Converters.Add(new ZoneUpdateRequestJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<ActionsApiEvents>();
            _services.AddSingleton<CertificateActionsApiEvents>();
            _services.AddSingleton<CertificatesApiEvents>();
            _services.AddSingleton<DataCentersApiEvents>();
            _services.AddSingleton<FirewallActionsApiEvents>();
            _services.AddSingleton<FirewallsApiEvents>();
            _services.AddSingleton<FloatingIPActionsApiEvents>();
            _services.AddSingleton<FloatingIPsApiEvents>();
            _services.AddSingleton<ISOsApiEvents>();
            _services.AddSingleton<ImageActionsApiEvents>();
            _services.AddSingleton<ImagesApiEvents>();
            _services.AddSingleton<LoadBalancerActionsApiEvents>();
            _services.AddSingleton<LoadBalancerTypesApiEvents>();
            _services.AddSingleton<LoadBalancersApiEvents>();
            _services.AddSingleton<LocationsApiEvents>();
            _services.AddSingleton<NetworkActionsApiEvents>();
            _services.AddSingleton<NetworksApiEvents>();
            _services.AddSingleton<PlacementGroupsApiEvents>();
            _services.AddSingleton<PricingApiEvents>();
            _services.AddSingleton<PrimaryIPActionsApiEvents>();
            _services.AddSingleton<PrimaryIPsApiEvents>();
            _services.AddSingleton<SSHKeysApiEvents>();
            _services.AddSingleton<ServerActionsApiEvents>();
            _services.AddSingleton<ServerTypesApiEvents>();
            _services.AddSingleton<ServersApiEvents>();
            _services.AddSingleton<VolumeActionsApiEvents>();
            _services.AddSingleton<VolumesApiEvents>();
            _services.AddSingleton<ZoneActionsApiEvents>();
            _services.AddSingleton<ZoneRRSetActionsApiEvents>();
            _services.AddSingleton<ZoneRRSetsApiEvents>();
            _services.AddSingleton<ZonesApiEvents>();
            OnHostConfigurationCreated();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(Action<IHttpClientBuilder>? builder = null)
        {
            return AddApiHttpClients((Action<IServiceProvider, HttpClient>?)null, builder);
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(
            Action<HttpClient>? client,
            Action<IHttpClientBuilder>? builder = null)
        {
            var wrapped = client != null ? new Action<IServiceProvider, HttpClient>((_, httpClient) =>
            {
                client(httpClient);
            }) : null;
            return AddApiHttpClients(wrapped, builder);
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(
            Action<IServiceProvider, HttpClient>? client,
            Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = (_, c) => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IActionsApi, ActionsApi>("HCloudAPI.Api.IActionsApi", client));
            builders.Add(_services.AddHttpClient<ICertificateActionsApi, CertificateActionsApi>("HCloudAPI.Api.ICertificateActionsApi", client));
            builders.Add(_services.AddHttpClient<ICertificatesApi, CertificatesApi>("HCloudAPI.Api.ICertificatesApi", client));
            builders.Add(_services.AddHttpClient<IDataCentersApi, DataCentersApi>("HCloudAPI.Api.IDataCentersApi", client));
            builders.Add(_services.AddHttpClient<IFirewallActionsApi, FirewallActionsApi>("HCloudAPI.Api.IFirewallActionsApi", client));
            builders.Add(_services.AddHttpClient<IFirewallsApi, FirewallsApi>("HCloudAPI.Api.IFirewallsApi", client));
            builders.Add(_services.AddHttpClient<IFloatingIPActionsApi, FloatingIPActionsApi>("HCloudAPI.Api.IFloatingIPActionsApi", client));
            builders.Add(_services.AddHttpClient<IFloatingIPsApi, FloatingIPsApi>("HCloudAPI.Api.IFloatingIPsApi", client));
            builders.Add(_services.AddHttpClient<IISOsApi, ISOsApi>("HCloudAPI.Api.IISOsApi", client));
            builders.Add(_services.AddHttpClient<IImageActionsApi, ImageActionsApi>("HCloudAPI.Api.IImageActionsApi", client));
            builders.Add(_services.AddHttpClient<IImagesApi, ImagesApi>("HCloudAPI.Api.IImagesApi", client));
            builders.Add(_services.AddHttpClient<ILoadBalancerActionsApi, LoadBalancerActionsApi>("HCloudAPI.Api.ILoadBalancerActionsApi", client));
            builders.Add(_services.AddHttpClient<ILoadBalancerTypesApi, LoadBalancerTypesApi>("HCloudAPI.Api.ILoadBalancerTypesApi", client));
            builders.Add(_services.AddHttpClient<ILoadBalancersApi, LoadBalancersApi>("HCloudAPI.Api.ILoadBalancersApi", client));
            builders.Add(_services.AddHttpClient<ILocationsApi, LocationsApi>("HCloudAPI.Api.ILocationsApi", client));
            builders.Add(_services.AddHttpClient<INetworkActionsApi, NetworkActionsApi>("HCloudAPI.Api.INetworkActionsApi", client));
            builders.Add(_services.AddHttpClient<INetworksApi, NetworksApi>("HCloudAPI.Api.INetworksApi", client));
            builders.Add(_services.AddHttpClient<IPlacementGroupsApi, PlacementGroupsApi>("HCloudAPI.Api.IPlacementGroupsApi", client));
            builders.Add(_services.AddHttpClient<IPricingApi, PricingApi>("HCloudAPI.Api.IPricingApi", client));
            builders.Add(_services.AddHttpClient<IPrimaryIPActionsApi, PrimaryIPActionsApi>("HCloudAPI.Api.IPrimaryIPActionsApi", client));
            builders.Add(_services.AddHttpClient<IPrimaryIPsApi, PrimaryIPsApi>("HCloudAPI.Api.IPrimaryIPsApi", client));
            builders.Add(_services.AddHttpClient<ISSHKeysApi, SSHKeysApi>("HCloudAPI.Api.ISSHKeysApi", client));
            builders.Add(_services.AddHttpClient<IServerActionsApi, ServerActionsApi>("HCloudAPI.Api.IServerActionsApi", client));
            builders.Add(_services.AddHttpClient<IServerTypesApi, ServerTypesApi>("HCloudAPI.Api.IServerTypesApi", client));
            builders.Add(_services.AddHttpClient<IServersApi, ServersApi>("HCloudAPI.Api.IServersApi", client));
            builders.Add(_services.AddHttpClient<IVolumeActionsApi, VolumeActionsApi>("HCloudAPI.Api.IVolumeActionsApi", client));
            builders.Add(_services.AddHttpClient<IVolumesApi, VolumesApi>("HCloudAPI.Api.IVolumesApi", client));
            builders.Add(_services.AddHttpClient<IZoneActionsApi, ZoneActionsApi>("HCloudAPI.Api.IZoneActionsApi", client));
            builders.Add(_services.AddHttpClient<IZoneRRSetActionsApi, ZoneRRSetActionsApi>("HCloudAPI.Api.IZoneRRSetActionsApi", client));
            builders.Add(_services.AddHttpClient<IZoneRRSetsApi, ZoneRRSetsApi>("HCloudAPI.Api.IZoneRRSetsApi", client));
            builders.Add(_services.AddHttpClient<IZonesApi, ZonesApi>("HCloudAPI.Api.IZonesApi", client));

            foreach (IHttpClientBuilder instance in builders)
            {
                OnAddApiHttpClientBuilder(instance);
                builder?.Invoke(instance);
            }

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Applies configuration to each HttpClient after registration.
        /// Implement this partial method in a separate file to provide custom defaults;
        /// the caller's <c>builder</c> action runs after.
        /// </summary>
        /// <param name="builder"></param>
        partial void OnAddApiHttpClientBuilder(IHttpClientBuilder builder);

        /// <summary>
        /// Called at the end of the constructor after all JSON converters and services are registered.
        /// Implement this partial method to further configure <c>_jsonOptions</c> or register additional singletons via <c>_services</c>.
        /// </summary>
        partial void OnHostConfigurationCreated();

        /// <summary>
        /// Called after all services have been registered.
        /// Implement this partial method to register additional services.
        /// </summary>
        /// <param name="services"></param>
        partial void OnServicesAdded(IServiceCollection services);

        internal void NotifyServicesAdded(IServiceCollection services) => OnServicesAdded(services);

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
