// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */
#nullable enable

using System;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace HCloudAPI.Clients
{
    /// <summary>
    /// Provides a token to the api clients. Tokens will be rate limited based on the provided TimeSpan.
    /// </summary>
    /// <typeparam name="TTokenBase"></typeparam>
    public class RateLimitProvider<TTokenBase> : TokenProvider<TTokenBase> where TTokenBase : TokenBase
    {
        /// <summary>
        /// Dictionary mapping header names to channels of available tokens for rate limiting.
        /// Each channel buffers tokens that have become available and are ready for use.
        /// </summary>
        protected internal Dictionary<string, global::System.Threading.Channels.Channel<TTokenBase>> AvailableTokens { get; } = new();

        /// <summary>
        /// Instantiates a ThrottledTokenProvider. Your tokens will be rate limited based on the token's timeout.
        /// </summary>
        /// <param name="container"></param>
        public RateLimitProvider(TokenContainer<TTokenBase> container) : base()
        {
            foreach(TTokenBase token in container.Tokens)
                token.StartTimer(token.Timeout ?? TimeSpan.FromMilliseconds(40));

            global::System.Threading.Channels.BoundedChannelOptions options = new global::System.Threading.Channels.BoundedChannelOptions(container.Tokens.Count)
            {
                FullMode = global::System.Threading.Channels.BoundedChannelFullMode.DropWrite
            };

            AvailableTokens.Add(string.Empty, global::System.Threading.Channels.Channel.CreateBounded<TTokenBase>(options));

            foreach (var availableToken in AvailableTokens)
                foreach(TTokenBase token in container.Tokens)
                {
                    token.TokenBecameAvailable += ((sender) => availableToken.Value.Writer.TryWrite((TTokenBase)sender));
                }
        }

        /// <inheritdoc/>
        protected internal override async System.Threading.Tasks.ValueTask<TTokenBase> GetAsync(string header = "", System.Threading.CancellationToken cancellation = default)
        {
            if (!AvailableTokens.TryGetValue(header, out global::System.Threading.Channels.Channel<TTokenBase>? tokens))
                throw new KeyNotFoundException($"Could not locate a token for header '{header}'.");

            return await tokens.Reader.ReadAsync(cancellation).ConfigureAwait(false);
        }
    }
    
    /// <summary>
    /// Handles proactive rate-limit prevention.
    /// </summary>
    public class GradualRateLimitingHandler : DelegatingHandler
    {
        private readonly object _lock = new();
        private int _remainingRequests = int.MaxValue;
        private int _maxLimit = 3600;
        private DateTimeOffset _resetTime = DateTimeOffset.MinValue;

        protected override async Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request, 
            CancellationToken cancellationToken)
        {
            TimeSpan delay = TimeSpan.Zero;

            lock (_lock)
            {
                if (_remainingRequests <= 0)
                {
                    var now = DateTimeOffset.UtcNow;
                    if (now < _resetTime)
                    {
                        var totalRemainingTime = _resetTime - now;
                        int missingRequests = _maxLimit; 
                        double secondsPerRequest = totalRemainingTime.TotalSeconds / missingRequests;

                        delay = TimeSpan.FromSeconds(Math.Max(1, secondsPerRequest));
                    }
                }
            }

            if (delay > TimeSpan.Zero)
            {
                await Task.Delay(delay, cancellationToken);
            }

            var response = await base.SendAsync(request, cancellationToken);
            ExtractRateLimitHeaders(response);

            return response;
        }

        private void ExtractRateLimitHeaders(HttpResponseMessage response)
        {
            lock (_lock)
            {
                if (response.Headers.TryGetValues("RateLimit-Limit", out var limitValues) &&
                    int.TryParse(limitValues.FirstOrDefault(), out var limit))
                {
                    _maxLimit = limit;
                }

                if (response.Headers.TryGetValues("RateLimit-Remaining", out var remainingValues) &&
                    int.TryParse(remainingValues.FirstOrDefault(), out var remaining))
                {
                    _remainingRequests = remaining;
                }

                if (response.Headers.TryGetValues("RateLimit-Reset", out var resetValues) &&
                    long.TryParse(resetValues.FirstOrDefault(), out var resetUnixTime))
                {
                    _resetTime = DateTimeOffset.FromUnixTimeSeconds(resetUnixTime);
                }
            }
        }
    }

}
