// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// AttachServerIsoRequest
    /// </summary>
    public partial class AttachServerIsoRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AttachServerIsoRequest" /> class.
        /// </summary>
        /// <param name="iso">ID or name of ISO to attach to the Server as listed in GET &#x60;/isos&#x60;.</param>
        [JsonConstructor]
        public AttachServerIsoRequest(string iso)
        {
            Iso = iso;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// ID or name of ISO to attach to the Server as listed in GET &#x60;/isos&#x60;.
        /// </summary>
        /// <value>ID or name of ISO to attach to the Server as listed in GET &#x60;/isos&#x60;.</value>
        /* <example>FreeBSD-11.0-RELEASE-amd64-dvd1</example> */
        [JsonPropertyName("iso")]
        public string Iso { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AttachServerIsoRequest {\n");
            sb.Append("  Iso: ").Append(Iso).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AttachServerIsoRequest" />
    /// </summary>
    public partial class AttachServerIsoRequestJsonConverter : JsonConverter<AttachServerIsoRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="AttachServerIsoRequestJsonConverter" /> class.
        /// </summary>
        public AttachServerIsoRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="AttachServerIsoRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AttachServerIsoRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> iso = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "iso":
                            iso = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!iso.IsSet)
                throw new ArgumentException("Property is required for class AttachServerIsoRequest.", nameof(iso));

            if (iso.IsSet && iso.Value == null)
                throw new ArgumentNullException(nameof(iso), "Property is not nullable for class AttachServerIsoRequest.");

            return new AttachServerIsoRequest(iso.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AttachServerIsoRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="attachServerIsoRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AttachServerIsoRequest attachServerIsoRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, attachServerIsoRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AttachServerIsoRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="attachServerIsoRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AttachServerIsoRequest attachServerIsoRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (attachServerIsoRequest.Iso == null)
                throw new ArgumentNullException(nameof(attachServerIsoRequest.Iso), "Property is required for class AttachServerIsoRequest.");

            writer.WriteString("iso", attachServerIsoRequest.Iso);
        }
    }
}
