// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// CreateZoneResponse
    /// </summary>
    public partial class CreateZoneResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateZoneResponse" /> class.
        /// </summary>
        /// <param name="zone">zone</param>
        /// <param name="action">action</param>
        [JsonConstructor]
        public CreateZoneResponse(Zone zone, Action action)
        {
            Zone = zone;
            Action = action;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Zone
        /// </summary>
        [JsonPropertyName("zone")]
        public Zone Zone { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [JsonPropertyName("action")]
        public Action Action { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateZoneResponse {\n");
            sb.Append("  Zone: ").Append(Zone).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateZoneResponse" />
    /// </summary>
    public partial class CreateZone201ResponseJsonConverter : JsonConverter<CreateZoneResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateZone201ResponseJsonConverter" /> class.
        /// </summary>
        public CreateZone201ResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateZoneResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateZoneResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Zone?> zone = default;
            Option<Action?> action = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "zone":
                            zone = new Option<Zone?>(JsonSerializer.Deserialize<Zone>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "action":
                            action = new Option<Action?>(JsonSerializer.Deserialize<Action>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!zone.IsSet)
                throw new ArgumentException("Property is required for class CreateZoneResponse.", nameof(zone));

            if (!action.IsSet)
                throw new ArgumentException("Property is required for class CreateZoneResponse.", nameof(action));

            if (zone.IsSet && zone.Value == null)
                throw new ArgumentNullException(nameof(zone), "Property is not nullable for class CreateZoneResponse.");

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class CreateZoneResponse.");

            return new CreateZoneResponse(zone.Value!, action.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CreateZoneResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createZoneResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateZoneResponse createZoneResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createZoneResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateZoneResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createZoneResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateZoneResponse createZoneResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createZoneResponse.Zone == null)
                throw new ArgumentNullException(nameof(createZoneResponse.Zone), "Property is required for class CreateZoneResponse.");

            if (createZoneResponse.Action == null)
                throw new ArgumentNullException(nameof(createZoneResponse.Action), "Property is required for class CreateZoneResponse.");

            writer.WritePropertyName("zone");
            JsonSerializer.Serialize(writer, createZoneResponse.Zone, jsonSerializerOptions);
            writer.WritePropertyName("action");
            JsonSerializer.Serialize(writer, createZoneResponse.Action, jsonSerializerOptions);
        }
    }
}
