// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// CreateServerImageResponse
    /// </summary>
    public partial class CreateServerImageResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateServerImageResponse" /> class.
        /// </summary>
        /// <param name="image">image</param>
        /// <param name="action">action</param>
        [JsonConstructor]
        public CreateServerImageResponse(Option<ListImagesResponseImagesInner?> image = default, Option<Action?> action = default)
        {
            ImageOption = image;
            ActionOption = action;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Image
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ListImagesResponseImagesInner?> ImageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [JsonPropertyName("image")]
        public ListImagesResponseImagesInner? Image { get { return this.ImageOption.Value; } set { this.ImageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Action
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Action?> ActionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [JsonPropertyName("action")]
        public Action? Action { get { return this.ActionOption.Value; } set { this.ActionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateServerImageResponse {\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateServerImageResponse" />
    /// </summary>
    public partial class CreateServerImage201ResponseJsonConverter : JsonConverter<CreateServerImageResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateServerImage201ResponseJsonConverter" /> class.
        /// </summary>
        public CreateServerImage201ResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateServerImageResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateServerImageResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ListImagesResponseImagesInner?> image = default;
            Option<Action?> action = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "image":
                            image = new Option<ListImagesResponseImagesInner?>(JsonSerializer.Deserialize<ListImagesResponseImagesInner>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "action":
                            action = new Option<Action?>(JsonSerializer.Deserialize<Action>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (image.IsSet && image.Value == null)
                throw new ArgumentNullException(nameof(image), "Property is not nullable for class CreateServerImageResponse.");

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class CreateServerImageResponse.");

            return new CreateServerImageResponse(image, action);
        }

        /// <summary>
        /// Serializes a <see cref="CreateServerImageResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createServerImageResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateServerImageResponse createServerImageResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createServerImageResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateServerImageResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createServerImageResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateServerImageResponse createServerImageResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createServerImageResponse.ImageOption.IsSet && createServerImageResponse.Image == null)
                throw new ArgumentNullException(nameof(createServerImageResponse.Image), "Property is required for class CreateServerImageResponse.");

            if (createServerImageResponse.ActionOption.IsSet && createServerImageResponse.Action == null)
                throw new ArgumentNullException(nameof(createServerImageResponse.Action), "Property is required for class CreateServerImageResponse.");

            if (createServerImageResponse.ImageOption.IsSet)
            {
                writer.WritePropertyName("image");
                JsonSerializer.Serialize(writer, createServerImageResponse.Image, jsonSerializerOptions);
            }
            if (createServerImageResponse.ActionOption.IsSet)
            {
                writer.WritePropertyName("action");
                JsonSerializer.Serialize(writer, createServerImageResponse.Action, jsonSerializerOptions);
            }
        }
    }
}
