// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// CreateImageRequest
    /// </summary>
    public partial class CreateImageRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateImageRequest" /> class.
        /// </summary>
        /// <param name="description">Description of the Image, will be auto-generated if not set.</param>
        /// <param name="type">Type of Image to create. (default to TypeEnum.Snapshot)</param>
        /// <param name="labels">User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#description/labels)\&quot;. </param>
        [JsonConstructor]
        public CreateImageRequest(Option<string?> description = default, Option<TypeEnum?> type = default, Option<Dictionary<string, string>?> labels = default)
        {
            DescriptionOption = description;
            TypeOption = type;
            LabelsOption = labels;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Type of Image to create.
        /// </summary>
        /// <value>Type of Image to create.</value>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Snapshot for value: snapshot
            /// </summary>
            Snapshot = 1,

            /// <summary>
            /// Enum Backup for value: backup
            /// </summary>
            Backup = 2
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("snapshot"))
                return TypeEnum.Snapshot;

            if (value.Equals("backup"))
                return TypeEnum.Backup;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("snapshot"))
                return TypeEnum.Snapshot;

            if (value.Equals("backup"))
                return TypeEnum.Backup;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.Snapshot)
                return "snapshot";

            if (value == TypeEnum.Backup)
                return "backup";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// Type of Image to create.
        /// </summary>
        /// <value>Type of Image to create.</value>
        /* <example>snapshot</example> */
        [JsonPropertyName("type")]
        public TypeEnum? Type { get { return this.TypeOption.Value; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Description of the Image, will be auto-generated if not set.
        /// </summary>
        /// <value>Description of the Image, will be auto-generated if not set.</value>
        /* <example>my image</example> */
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Labels
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> LabelsOption { get; private set; }

        /// <summary>
        /// User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#description/labels)\&quot;. 
        /// </summary>
        /// <value>User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#description/labels)\&quot;. </value>
        /* <example>{environment&#x3D;prod, example.com/my&#x3D;label, just-a-key&#x3D;}</example> */
        [JsonPropertyName("labels")]
        public Dictionary<string, string>? Labels { get { return this.LabelsOption.Value; } set { this.LabelsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateImageRequest {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateImageRequest" />
    /// </summary>
    public partial class CreateImageRequestJsonConverter : JsonConverter<CreateImageRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateImageRequestJsonConverter" /> class.
        /// </summary>
        public CreateImageRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateImageRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateImageRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> description = default;
            Option<CreateImageRequest.TypeEnum?> type = default;
            Option<Dictionary<string, string>?> labels = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<CreateImageRequest.TypeEnum?>(CreateImageRequest.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "labels":
                            labels = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class CreateImageRequest.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class CreateImageRequest.");

            if (labels.IsSet && labels.Value == null)
                throw new ArgumentNullException(nameof(labels), "Property is not nullable for class CreateImageRequest.");

            return new CreateImageRequest(description, type, labels);
        }

        /// <summary>
        /// Serializes a <see cref="CreateImageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createImageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateImageRequest createImageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createImageRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateImageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createImageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateImageRequest createImageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createImageRequest.DescriptionOption.IsSet && createImageRequest.Description == null)
                throw new ArgumentNullException(nameof(createImageRequest.Description), "Property is required for class CreateImageRequest.");

            if (createImageRequest.LabelsOption.IsSet && createImageRequest.Labels == null)
                throw new ArgumentNullException(nameof(createImageRequest.Labels), "Property is required for class CreateImageRequest.");

            if (createImageRequest.DescriptionOption.IsSet)
                writer.WriteString("description", createImageRequest.Description);

            var typeRawValue = CreateImageRequest.TypeEnumToJsonValue(createImageRequest.TypeOption.Value!.Value);
            writer.WriteString("type", typeRawValue);
            if (createImageRequest.LabelsOption.IsSet)
            {
                writer.WritePropertyName("labels");
                JsonSerializer.Serialize(writer, createImageRequest.Labels, jsonSerializerOptions);
            }
        }
    }
}
