// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// The &#x60;root_password&#x60; key in the reply contains the root password that can be used to access the booted rescue system. 
    /// </summary>
    public partial class EnableServerRescueResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnableServerRescueResponse" /> class.
        /// </summary>
        /// <param name="rootPassword">Password that will be set for this Server once the Action succeeds.</param>
        /// <param name="action">action</param>
        [JsonConstructor]
        public EnableServerRescueResponse(Option<string?> rootPassword = default, Option<Action?> action = default)
        {
            RootPasswordOption = rootPassword;
            ActionOption = action;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of RootPassword
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RootPasswordOption { get; private set; }

        /// <summary>
        /// Password that will be set for this Server once the Action succeeds.
        /// </summary>
        /// <value>Password that will be set for this Server once the Action succeeds.</value>
        /* <example>zCWbFhnu950dUTko5f40</example> */
        [JsonPropertyName("root_password")]
        public string? RootPassword { get { return this.RootPasswordOption.Value; } set { this.RootPasswordOption = new(value); } }

        /// <summary>
        /// Used to track the state of Action
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Action?> ActionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [JsonPropertyName("action")]
        public Action? Action { get { return this.ActionOption.Value; } set { this.ActionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnableServerRescueResponse {\n");
            sb.Append("  RootPassword: ").Append(RootPassword).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnableServerRescueResponse" />
    /// </summary>
    public partial class EnableServerRescue201ResponseJsonConverter : JsonConverter<EnableServerRescueResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="EnableServerRescue201ResponseJsonConverter" /> class.
        /// </summary>
        public EnableServerRescue201ResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="EnableServerRescueResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnableServerRescueResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> rootPassword = default;
            Option<Action?> action = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "root_password":
                            rootPassword = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action":
                            action = new Option<Action?>(JsonSerializer.Deserialize<Action>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (rootPassword.IsSet && rootPassword.Value == null)
                throw new ArgumentNullException(nameof(rootPassword), "Property is not nullable for class EnableServerRescueResponse.");

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class EnableServerRescueResponse.");

            return new EnableServerRescueResponse(rootPassword, action);
        }

        /// <summary>
        /// Serializes a <see cref="EnableServerRescueResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enableServerRescueResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnableServerRescueResponse enableServerRescueResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, enableServerRescueResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnableServerRescueResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enableServerRescueResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EnableServerRescueResponse enableServerRescueResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (enableServerRescueResponse.RootPasswordOption.IsSet && enableServerRescueResponse.RootPassword == null)
                throw new ArgumentNullException(nameof(enableServerRescueResponse.RootPassword), "Property is required for class EnableServerRescueResponse.");

            if (enableServerRescueResponse.ActionOption.IsSet && enableServerRescueResponse.Action == null)
                throw new ArgumentNullException(nameof(enableServerRescueResponse.Action), "Property is required for class EnableServerRescueResponse.");

            if (enableServerRescueResponse.RootPasswordOption.IsSet)
                writer.WriteString("root_password", enableServerRescueResponse.RootPassword);

            if (enableServerRescueResponse.ActionOption.IsSet)
            {
                writer.WritePropertyName("action");
                JsonSerializer.Serialize(writer, enableServerRescueResponse.Action, jsonSerializerOptions);
            }
        }
    }
}
