// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// FirewallResponseAppliedToInner
    /// </summary>
    public partial class FirewallResponseAppliedToInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FirewallResponseAppliedToInner" /> class.
        /// </summary>
        /// <param name="type">The type of resource to apply.</param>
        /// <param name="server">server</param>
        /// <param name="labelSelector">labelSelector</param>
        /// <param name="appliedToResources">Resources applied to via this [Label Selector](#description/label-selector). </param>
        [JsonConstructor]
        public FirewallResponseAppliedToInner(TypeEnum type, Option<FirewallResponseAppliedToInnerServer?> server = default, Option<FirewallResponseAppliedToInnerLabelSelector?> labelSelector = default, Option<List<FirewallResponseAppliedToInnerAppliedToResources>?> appliedToResources = default)
        {
            Type = type;
            ServerOption = server;
            LabelSelectorOption = labelSelector;
            AppliedToResourcesOption = appliedToResources;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The type of resource to apply.
        /// </summary>
        /// <value>The type of resource to apply.</value>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Server for value: server
            /// </summary>
            Server = 1,

            /// <summary>
            /// Enum LabelSelector for value: label_selector
            /// </summary>
            LabelSelector = 2
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("server"))
                return TypeEnum.Server;

            if (value.Equals("label_selector"))
                return TypeEnum.LabelSelector;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("server"))
                return TypeEnum.Server;

            if (value.Equals("label_selector"))
                return TypeEnum.LabelSelector;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.Server)
                return "server";

            if (value == TypeEnum.LabelSelector)
                return "label_selector";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The type of resource to apply.
        /// </summary>
        /// <value>The type of resource to apply.</value>
        /* <example>server</example> */
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Used to track the state of Server
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FirewallResponseAppliedToInnerServer?> ServerOption { get; private set; }

        /// <summary>
        /// Gets or Sets Server
        /// </summary>
        [JsonPropertyName("server")]
        public FirewallResponseAppliedToInnerServer? Server { get { return this.ServerOption.Value; } set { this.ServerOption = new(value); } }

        /// <summary>
        /// Used to track the state of LabelSelector
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FirewallResponseAppliedToInnerLabelSelector?> LabelSelectorOption { get; private set; }

        /// <summary>
        /// Gets or Sets LabelSelector
        /// </summary>
        [JsonPropertyName("label_selector")]
        public FirewallResponseAppliedToInnerLabelSelector? LabelSelector { get { return this.LabelSelectorOption.Value; } set { this.LabelSelectorOption = new(value); } }

        /// <summary>
        /// Used to track the state of AppliedToResources
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<FirewallResponseAppliedToInnerAppliedToResources>?> AppliedToResourcesOption { get; private set; }

        /// <summary>
        /// Resources applied to via this [Label Selector](#description/label-selector). 
        /// </summary>
        /// <value>Resources applied to via this [Label Selector](#description/label-selector). </value>
        [JsonPropertyName("applied_to_resources")]
        public List<FirewallResponseAppliedToInnerAppliedToResources>? AppliedToResources { get { return this.AppliedToResourcesOption.Value; } set { this.AppliedToResourcesOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FirewallResponseAppliedToInner {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("  LabelSelector: ").Append(LabelSelector).Append("\n");
            sb.Append("  AppliedToResources: ").Append(AppliedToResources).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FirewallResponseAppliedToInner" />
    /// </summary>
    public partial class FirewallResponseAppliedToInnerJsonConverter : JsonConverter<FirewallResponseAppliedToInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="FirewallResponseAppliedToInnerJsonConverter" /> class.
        /// </summary>
        public FirewallResponseAppliedToInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="FirewallResponseAppliedToInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FirewallResponseAppliedToInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<FirewallResponseAppliedToInner.TypeEnum?> type = default;
            Option<FirewallResponseAppliedToInnerServer?> server = default;
            Option<FirewallResponseAppliedToInnerLabelSelector?> labelSelector = default;
            Option<List<FirewallResponseAppliedToInnerAppliedToResources>?> appliedToResources = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<FirewallResponseAppliedToInner.TypeEnum?>(FirewallResponseAppliedToInner.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "server":
                            server = new Option<FirewallResponseAppliedToInnerServer?>(JsonSerializer.Deserialize<FirewallResponseAppliedToInnerServer>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "label_selector":
                            labelSelector = new Option<FirewallResponseAppliedToInnerLabelSelector?>(JsonSerializer.Deserialize<FirewallResponseAppliedToInnerLabelSelector>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "applied_to_resources":
                            appliedToResources = new Option<List<FirewallResponseAppliedToInnerAppliedToResources>?>(JsonSerializer.Deserialize<List<FirewallResponseAppliedToInnerAppliedToResources>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class FirewallResponseAppliedToInner.", nameof(type));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class FirewallResponseAppliedToInner.");

            if (server.IsSet && server.Value == null)
                throw new ArgumentNullException(nameof(server), "Property is not nullable for class FirewallResponseAppliedToInner.");

            if (labelSelector.IsSet && labelSelector.Value == null)
                throw new ArgumentNullException(nameof(labelSelector), "Property is not nullable for class FirewallResponseAppliedToInner.");

            if (appliedToResources.IsSet && appliedToResources.Value == null)
                throw new ArgumentNullException(nameof(appliedToResources), "Property is not nullable for class FirewallResponseAppliedToInner.");

            return new FirewallResponseAppliedToInner(type.Value!.Value!, server, labelSelector, appliedToResources);
        }

        /// <summary>
        /// Serializes a <see cref="FirewallResponseAppliedToInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="firewallResponseAppliedToInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FirewallResponseAppliedToInner firewallResponseAppliedToInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, firewallResponseAppliedToInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FirewallResponseAppliedToInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="firewallResponseAppliedToInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FirewallResponseAppliedToInner firewallResponseAppliedToInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (firewallResponseAppliedToInner.ServerOption.IsSet && firewallResponseAppliedToInner.Server == null)
                throw new ArgumentNullException(nameof(firewallResponseAppliedToInner.Server), "Property is required for class FirewallResponseAppliedToInner.");

            if (firewallResponseAppliedToInner.LabelSelectorOption.IsSet && firewallResponseAppliedToInner.LabelSelector == null)
                throw new ArgumentNullException(nameof(firewallResponseAppliedToInner.LabelSelector), "Property is required for class FirewallResponseAppliedToInner.");

            if (firewallResponseAppliedToInner.AppliedToResourcesOption.IsSet && firewallResponseAppliedToInner.AppliedToResources == null)
                throw new ArgumentNullException(nameof(firewallResponseAppliedToInner.AppliedToResources), "Property is required for class FirewallResponseAppliedToInner.");

            var typeRawValue = FirewallResponseAppliedToInner.TypeEnumToJsonValue(firewallResponseAppliedToInner.Type);
            writer.WriteString("type", typeRawValue);
            if (firewallResponseAppliedToInner.ServerOption.IsSet)
            {
                writer.WritePropertyName("server");
                JsonSerializer.Serialize(writer, firewallResponseAppliedToInner.Server, jsonSerializerOptions);
            }
            if (firewallResponseAppliedToInner.LabelSelectorOption.IsSet)
            {
                writer.WritePropertyName("label_selector");
                JsonSerializer.Serialize(writer, firewallResponseAppliedToInner.LabelSelector, jsonSerializerOptions);
            }
            if (firewallResponseAppliedToInner.AppliedToResourcesOption.IsSet)
            {
                writer.WritePropertyName("applied_to_resources");
                JsonSerializer.Serialize(writer, firewallResponseAppliedToInner.AppliedToResources, jsonSerializerOptions);
            }
        }
    }
}
