// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// FloatingIPActionsAssignRequest
    /// </summary>
    public partial class FloatingIPActionsAssignRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FloatingIPActionsAssignRequest" /> class.
        /// </summary>
        /// <param name="server">[Server](#tag/servers) the [Floating IP](#tag/floating-ips) is assigned to.  &#x60;null&#x60; if not assigned. </param>
        [JsonConstructor]
        public FloatingIPActionsAssignRequest(long? server = default)
        {
            Server = server;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// [Server](#tag/servers) the [Floating IP](#tag/floating-ips) is assigned to.  &#x60;null&#x60; if not assigned. 
        /// </summary>
        /// <value>[Server](#tag/servers) the [Floating IP](#tag/floating-ips) is assigned to.  &#x60;null&#x60; if not assigned. </value>
        /* <example>42</example> */
        [JsonPropertyName("server")]
        public long? Server { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FloatingIPActionsAssignRequest {\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FloatingIPActionsAssignRequest" />
    /// </summary>
    public partial class FloatingIPActionsAssignRequestJsonConverter : JsonConverter<FloatingIPActionsAssignRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="FloatingIPActionsAssignRequestJsonConverter" /> class.
        /// </summary>
        public FloatingIPActionsAssignRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="FloatingIPActionsAssignRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FloatingIPActionsAssignRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> server = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "server":
                            server = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!server.IsSet)
                throw new ArgumentException("Property is required for class FloatingIPActionsAssignRequest.", nameof(server));

            return new FloatingIPActionsAssignRequest(server.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="FloatingIPActionsAssignRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="floatingIPActionsAssignRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FloatingIPActionsAssignRequest floatingIPActionsAssignRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, floatingIPActionsAssignRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FloatingIPActionsAssignRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="floatingIPActionsAssignRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FloatingIPActionsAssignRequest floatingIPActionsAssignRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (floatingIPActionsAssignRequest.Server != null)
                writer.WriteNumber("server", floatingIPActionsAssignRequest.Server.Value);
            else
                writer.WriteNull("server");
        }
    }
}
