// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// GetActions4xxResponseError
    /// </summary>
    public partial class GetActions4xxResponseError : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetActions4xxResponseError" /> class.
        /// </summary>
        /// <param name="code">Error code for machines.</param>
        /// <param name="message">Error message for humans.</param>
        /// <param name="details">Details about the error.</param>
        [JsonConstructor]
        public GetActions4xxResponseError(string code, string message, Option<Object?> details = default)
        {
            Code = code;
            Message = message;
            DetailsOption = details;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Error code for machines.
        /// </summary>
        /// <value>Error code for machines.</value>
        [JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>
        /// Error message for humans.
        /// </summary>
        /// <value>Error message for humans.</value>
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Used to track the state of Details
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> DetailsOption { get; private set; }

        /// <summary>
        /// Details about the error.
        /// </summary>
        /// <value>Details about the error.</value>
        [JsonPropertyName("details")]
        public Object? Details { get { return this.DetailsOption.Value; } set { this.DetailsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetActions4xxResponseError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetActions4xxResponseError" />
    /// </summary>
    public partial class GetActions4xxResponseErrorJsonConverter : JsonConverter<GetActions4xxResponseError>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GetActions4xxResponseErrorJsonConverter" /> class.
        /// </summary>
        public GetActions4xxResponseErrorJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="GetActions4xxResponseError" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetActions4xxResponseError Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> code = default;
            Option<string?> message = default;
            Option<Object?> details = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "details":
                            details = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!code.IsSet)
                throw new ArgumentException("Property is required for class GetActions4xxResponseError.", nameof(code));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class GetActions4xxResponseError.", nameof(message));

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class GetActions4xxResponseError.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class GetActions4xxResponseError.");

            return new GetActions4xxResponseError(code.Value!, message.Value!, details);
        }

        /// <summary>
        /// Serializes a <see cref="GetActions4xxResponseError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getActions4xxResponseError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetActions4xxResponseError getActions4xxResponseError, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getActions4xxResponseError, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetActions4xxResponseError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getActions4xxResponseError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetActions4xxResponseError getActions4xxResponseError, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getActions4xxResponseError.Code == null)
                throw new ArgumentNullException(nameof(getActions4xxResponseError.Code), "Property is required for class GetActions4xxResponseError.");

            if (getActions4xxResponseError.Message == null)
                throw new ArgumentNullException(nameof(getActions4xxResponseError.Message), "Property is required for class GetActions4xxResponseError.");

            writer.WriteString("code", getActions4xxResponseError.Code);

            writer.WriteString("message", getActions4xxResponseError.Message);

            if (getActions4xxResponseError.DetailsOption.IsSet)
                if (getActions4xxResponseError.DetailsOption.Value != null)
                {
                    writer.WritePropertyName("details");
                    JsonSerializer.Serialize(writer, getActions4xxResponseError.Details, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("details");
        }
    }
}
