// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// GetDatacenterResponseDatacenter
    /// </summary>
    public partial class GetDatacenterResponseDatacenter : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDatacenterResponseDatacenter" /> class.
        /// </summary>
        /// <param name="id">ID of the [Data Center](#tag/data-centers).</param>
        /// <param name="name">Unique name for the [Data Center](#tag/data-centers).  May be used as a more descriptive identifier. </param>
        /// <param name="description">Descriptive name for the [Data Center](#tag/data-centers).  Desired to be easy to understand for humans. May change for cosmetic reasons. Must not be used as an identifier. </param>
        /// <param name="location">location</param>
        /// <param name="serverTypes">serverTypes</param>
        [JsonConstructor]
        public GetDatacenterResponseDatacenter(long id, string name, string description, ListDatacentersResponseDatacentersInnerLocation location, GetDatacenterResponseDatacenterServerTypes serverTypes)
        {
            Id = id;
            Name = name;
            Description = description;
            Location = location;
            ServerTypes = serverTypes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// ID of the [Data Center](#tag/data-centers).
        /// </summary>
        /// <value>ID of the [Data Center](#tag/data-centers).</value>
        /* <example>42</example> */
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Unique name for the [Data Center](#tag/data-centers).  May be used as a more descriptive identifier. 
        /// </summary>
        /// <value>Unique name for the [Data Center](#tag/data-centers).  May be used as a more descriptive identifier. </value>
        /* <example>fsn1-dc8</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Descriptive name for the [Data Center](#tag/data-centers).  Desired to be easy to understand for humans. May change for cosmetic reasons. Must not be used as an identifier. 
        /// </summary>
        /// <value>Descriptive name for the [Data Center](#tag/data-centers).  Desired to be easy to understand for humans. May change for cosmetic reasons. Must not be used as an identifier. </value>
        /* <example>Falkenstein DC Park 8</example> */
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [JsonPropertyName("location")]
        public ListDatacentersResponseDatacentersInnerLocation Location { get; set; }

        /// <summary>
        /// Gets or Sets ServerTypes
        /// </summary>
        [JsonPropertyName("server_types")]
        [Obsolete]
        public GetDatacenterResponseDatacenterServerTypes ServerTypes { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetDatacenterResponseDatacenter {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  ServerTypes: ").Append(ServerTypes).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (long) maximum
            if (this.Id > (long)9007199254740991)
            {
                yield return new ValidationResult("Invalid value for Id, must be a value less than or equal to 9007199254740991.", new [] { "Id" });
            }

            // Id (long) minimum
            if (this.Id < (long)1)
            {
                yield return new ValidationResult("Invalid value for Id, must be a value greater than or equal to 1.", new [] { "Id" });
            }

            if (this.Name != null) {
                // Name (string) pattern
                Regex regexName = new Regex(@"^[a-z0-9]+(-?[a-z0-9]*)*$", RegexOptions.CultureInvariant);

                if (!regexName.Match(this.Name).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetDatacenterResponseDatacenter" />
    /// </summary>
    public partial class GetDatacenterResponseDatacenterJsonConverter : JsonConverter<GetDatacenterResponseDatacenter>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GetDatacenterResponseDatacenterJsonConverter" /> class.
        /// </summary>
        public GetDatacenterResponseDatacenterJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="GetDatacenterResponseDatacenter" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetDatacenterResponseDatacenter Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<string?> name = default;
            Option<string?> description = default;
            Option<ListDatacentersResponseDatacentersInnerLocation?> location = default;
            Option<GetDatacenterResponseDatacenterServerTypes?> serverTypes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "location":
                            location = new Option<ListDatacentersResponseDatacentersInnerLocation?>(JsonSerializer.Deserialize<ListDatacentersResponseDatacentersInnerLocation>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "server_types":
                            serverTypes = new Option<GetDatacenterResponseDatacenterServerTypes?>(JsonSerializer.Deserialize<GetDatacenterResponseDatacenterServerTypes>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class GetDatacenterResponseDatacenter.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class GetDatacenterResponseDatacenter.", nameof(name));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class GetDatacenterResponseDatacenter.", nameof(description));

            if (!location.IsSet)
                throw new ArgumentException("Property is required for class GetDatacenterResponseDatacenter.", nameof(location));

            if (!serverTypes.IsSet)
                throw new ArgumentException("Property is required for class GetDatacenterResponseDatacenter.", nameof(serverTypes));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class GetDatacenterResponseDatacenter.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class GetDatacenterResponseDatacenter.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class GetDatacenterResponseDatacenter.");

            if (location.IsSet && location.Value == null)
                throw new ArgumentNullException(nameof(location), "Property is not nullable for class GetDatacenterResponseDatacenter.");

            if (serverTypes.IsSet && serverTypes.Value == null)
                throw new ArgumentNullException(nameof(serverTypes), "Property is not nullable for class GetDatacenterResponseDatacenter.");

            return new GetDatacenterResponseDatacenter(id.Value!.Value!, name.Value!, description.Value!, location.Value!, serverTypes.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetDatacenterResponseDatacenter" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getDatacenterResponseDatacenter"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetDatacenterResponseDatacenter getDatacenterResponseDatacenter, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getDatacenterResponseDatacenter, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetDatacenterResponseDatacenter" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getDatacenterResponseDatacenter"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetDatacenterResponseDatacenter getDatacenterResponseDatacenter, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getDatacenterResponseDatacenter.Name == null)
                throw new ArgumentNullException(nameof(getDatacenterResponseDatacenter.Name), "Property is required for class GetDatacenterResponseDatacenter.");

            if (getDatacenterResponseDatacenter.Description == null)
                throw new ArgumentNullException(nameof(getDatacenterResponseDatacenter.Description), "Property is required for class GetDatacenterResponseDatacenter.");

            if (getDatacenterResponseDatacenter.Location == null)
                throw new ArgumentNullException(nameof(getDatacenterResponseDatacenter.Location), "Property is required for class GetDatacenterResponseDatacenter.");

            if (getDatacenterResponseDatacenter.ServerTypes == null)
                throw new ArgumentNullException(nameof(getDatacenterResponseDatacenter.ServerTypes), "Property is required for class GetDatacenterResponseDatacenter.");

            writer.WriteNumber("id", getDatacenterResponseDatacenter.Id);

            writer.WriteString("name", getDatacenterResponseDatacenter.Name);

            writer.WriteString("description", getDatacenterResponseDatacenter.Description);

            writer.WritePropertyName("location");
            JsonSerializer.Serialize(writer, getDatacenterResponseDatacenter.Location, jsonSerializerOptions);
            writer.WritePropertyName("server_types");
            JsonSerializer.Serialize(writer, getDatacenterResponseDatacenter.ServerTypes, jsonSerializerOptions);
        }
    }
}
