// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// GetLoadBalancerMetricsResponseMetrics
    /// </summary>
    public partial class GetLoadBalancerMetricsResponseMetrics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetLoadBalancerMetricsResponseMetrics" /> class.
        /// </summary>
        /// <param name="start">Start of period of metrics reported (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).</param>
        /// <param name="end">End of period of metrics reported (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).</param>
        /// <param name="step">Resolution of results in seconds.</param>
        /// <param name="timeSeries">Hash with timeseries information, containing the name of timeseries as key.</param>
        [JsonConstructor]
        public GetLoadBalancerMetricsResponseMetrics(DateTime start, DateTime end, decimal step, Dictionary<string, GetLoadBalancerMetricsResponseMetricsTimeSeriesValue> timeSeries)
        {
            Start = start;
            End = end;
            Step = step;
            TimeSeries = timeSeries;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Start of period of metrics reported (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
        /// </summary>
        /// <value>Start of period of metrics reported (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).</value>
        /* <example>2017-01-01T00:00:00Z</example> */
        [JsonPropertyName("start")]
        public DateTime Start { get; set; }

        /// <summary>
        /// End of period of metrics reported (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
        /// </summary>
        /// <value>End of period of metrics reported (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).</value>
        /* <example>2017-01-01T23:00:00Z</example> */
        [JsonPropertyName("end")]
        public DateTime End { get; set; }

        /// <summary>
        /// Resolution of results in seconds.
        /// </summary>
        /// <value>Resolution of results in seconds.</value>
        /* <example>60</example> */
        [JsonPropertyName("step")]
        public decimal Step { get; set; }

        /// <summary>
        /// Hash with timeseries information, containing the name of timeseries as key.
        /// </summary>
        /// <value>Hash with timeseries information, containing the name of timeseries as key.</value>
        /* <example>{&quot;name_of_timeseries&quot;:{&quot;values&quot;:[[1.435781470622E9,&quot;42&quot;],[1.435781471622E9,&quot;43&quot;]]}}</example> */
        [JsonPropertyName("time_series")]
        public Dictionary<string, GetLoadBalancerMetricsResponseMetricsTimeSeriesValue> TimeSeries { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetLoadBalancerMetricsResponseMetrics {\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("  Step: ").Append(Step).Append("\n");
            sb.Append("  TimeSeries: ").Append(TimeSeries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetLoadBalancerMetricsResponseMetrics" />
    /// </summary>
    public partial class GetLoadBalancerMetricsResponseMetricsJsonConverter : JsonConverter<GetLoadBalancerMetricsResponseMetrics>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GetLoadBalancerMetricsResponseMetricsJsonConverter" /> class.
        /// </summary>
        public GetLoadBalancerMetricsResponseMetricsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize Start
        /// </summary>
        public string StartFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize End
        /// </summary>
        public string EndFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="GetLoadBalancerMetricsResponseMetrics" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetLoadBalancerMetricsResponseMetrics Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateTime?> start = default;
            Option<DateTime?> end = default;
            Option<decimal?> step = default;
            Option<Dictionary<string, GetLoadBalancerMetricsResponseMetricsTimeSeriesValue>?> timeSeries = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "start":
                            start = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "end":
                            end = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "step":
                            step = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "time_series":
                            timeSeries = new Option<Dictionary<string, GetLoadBalancerMetricsResponseMetricsTimeSeriesValue>?>(JsonSerializer.Deserialize<Dictionary<string, GetLoadBalancerMetricsResponseMetricsTimeSeriesValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!start.IsSet)
                throw new ArgumentException("Property is required for class GetLoadBalancerMetricsResponseMetrics.", nameof(start));

            if (!end.IsSet)
                throw new ArgumentException("Property is required for class GetLoadBalancerMetricsResponseMetrics.", nameof(end));

            if (!step.IsSet)
                throw new ArgumentException("Property is required for class GetLoadBalancerMetricsResponseMetrics.", nameof(step));

            if (!timeSeries.IsSet)
                throw new ArgumentException("Property is required for class GetLoadBalancerMetricsResponseMetrics.", nameof(timeSeries));

            if (start.IsSet && start.Value == null)
                throw new ArgumentNullException(nameof(start), "Property is not nullable for class GetLoadBalancerMetricsResponseMetrics.");

            if (end.IsSet && end.Value == null)
                throw new ArgumentNullException(nameof(end), "Property is not nullable for class GetLoadBalancerMetricsResponseMetrics.");

            if (step.IsSet && step.Value == null)
                throw new ArgumentNullException(nameof(step), "Property is not nullable for class GetLoadBalancerMetricsResponseMetrics.");

            if (timeSeries.IsSet && timeSeries.Value == null)
                throw new ArgumentNullException(nameof(timeSeries), "Property is not nullable for class GetLoadBalancerMetricsResponseMetrics.");

            return new GetLoadBalancerMetricsResponseMetrics(start.Value!.Value!, end.Value!.Value!, step.Value!.Value!, timeSeries.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetLoadBalancerMetricsResponseMetrics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getLoadBalancerMetricsResponseMetrics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetLoadBalancerMetricsResponseMetrics getLoadBalancerMetricsResponseMetrics, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getLoadBalancerMetricsResponseMetrics, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetLoadBalancerMetricsResponseMetrics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getLoadBalancerMetricsResponseMetrics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetLoadBalancerMetricsResponseMetrics getLoadBalancerMetricsResponseMetrics, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getLoadBalancerMetricsResponseMetrics.TimeSeries == null)
                throw new ArgumentNullException(nameof(getLoadBalancerMetricsResponseMetrics.TimeSeries), "Property is required for class GetLoadBalancerMetricsResponseMetrics.");

            writer.WriteString("start", getLoadBalancerMetricsResponseMetrics.Start.ToString(StartFormat));

            writer.WriteString("end", getLoadBalancerMetricsResponseMetrics.End.ToString(EndFormat));

            writer.WriteNumber("step", getLoadBalancerMetricsResponseMetrics.Step);

            writer.WritePropertyName("time_series");
            JsonSerializer.Serialize(writer, getLoadBalancerMetricsResponseMetrics.TimeSeries, jsonSerializerOptions);
        }
    }
}
