// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// GetPricingResponsePricingPrimaryIpsInner
    /// </summary>
    public partial class GetPricingResponsePricingPrimaryIpsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPricingResponsePricingPrimaryIpsInner" /> class.
        /// </summary>
        /// <param name="type">Type of [Primary IP](#tag/primary-ips) the price is for.</param>
        /// <param name="prices">Price of the [Primary IP](#tag/primary-ips) type per [Location](#tag/locations).</param>
        [JsonConstructor]
        public GetPricingResponsePricingPrimaryIpsInner(TypeEnum type, List<GetPricingResponsePricingPrimaryIpsInnerPricesInner> prices)
        {
            Type = type;
            Prices = prices;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Type of [Primary IP](#tag/primary-ips) the price is for.
        /// </summary>
        /// <value>Type of [Primary IP](#tag/primary-ips) the price is for.</value>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Ipv4 for value: ipv4
            /// </summary>
            Ipv4 = 1,

            /// <summary>
            /// Enum Ipv6 for value: ipv6
            /// </summary>
            Ipv6 = 2
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("ipv4"))
                return TypeEnum.Ipv4;

            if (value.Equals("ipv6"))
                return TypeEnum.Ipv6;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ipv4"))
                return TypeEnum.Ipv4;

            if (value.Equals("ipv6"))
                return TypeEnum.Ipv6;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.Ipv4)
                return "ipv4";

            if (value == TypeEnum.Ipv6)
                return "ipv6";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Type of [Primary IP](#tag/primary-ips) the price is for.
        /// </summary>
        /// <value>Type of [Primary IP](#tag/primary-ips) the price is for.</value>
        /* <example>ipv4</example> */
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Price of the [Primary IP](#tag/primary-ips) type per [Location](#tag/locations).
        /// </summary>
        /// <value>Price of the [Primary IP](#tag/primary-ips) type per [Location](#tag/locations).</value>
        [JsonPropertyName("prices")]
        public List<GetPricingResponsePricingPrimaryIpsInnerPricesInner> Prices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetPricingResponsePricingPrimaryIpsInner {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Prices: ").Append(Prices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetPricingResponsePricingPrimaryIpsInner" />
    /// </summary>
    public partial class GetPricingResponsePricingPrimaryIpsInnerJsonConverter : JsonConverter<GetPricingResponsePricingPrimaryIpsInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GetPricingResponsePricingPrimaryIpsInnerJsonConverter" /> class.
        /// </summary>
        public GetPricingResponsePricingPrimaryIpsInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="GetPricingResponsePricingPrimaryIpsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetPricingResponsePricingPrimaryIpsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<GetPricingResponsePricingPrimaryIpsInner.TypeEnum?> type = default;
            Option<List<GetPricingResponsePricingPrimaryIpsInnerPricesInner>?> prices = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<GetPricingResponsePricingPrimaryIpsInner.TypeEnum?>(GetPricingResponsePricingPrimaryIpsInner.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "prices":
                            prices = new Option<List<GetPricingResponsePricingPrimaryIpsInnerPricesInner>?>(JsonSerializer.Deserialize<List<GetPricingResponsePricingPrimaryIpsInnerPricesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class GetPricingResponsePricingPrimaryIpsInner.", nameof(type));

            if (!prices.IsSet)
                throw new ArgumentException("Property is required for class GetPricingResponsePricingPrimaryIpsInner.", nameof(prices));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class GetPricingResponsePricingPrimaryIpsInner.");

            if (prices.IsSet && prices.Value == null)
                throw new ArgumentNullException(nameof(prices), "Property is not nullable for class GetPricingResponsePricingPrimaryIpsInner.");

            return new GetPricingResponsePricingPrimaryIpsInner(type.Value!.Value!, prices.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetPricingResponsePricingPrimaryIpsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getPricingResponsePricingPrimaryIpsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetPricingResponsePricingPrimaryIpsInner getPricingResponsePricingPrimaryIpsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getPricingResponsePricingPrimaryIpsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetPricingResponsePricingPrimaryIpsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getPricingResponsePricingPrimaryIpsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetPricingResponsePricingPrimaryIpsInner getPricingResponsePricingPrimaryIpsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getPricingResponsePricingPrimaryIpsInner.Prices == null)
                throw new ArgumentNullException(nameof(getPricingResponsePricingPrimaryIpsInner.Prices), "Property is required for class GetPricingResponsePricingPrimaryIpsInner.");

            var typeRawValue = GetPricingResponsePricingPrimaryIpsInner.TypeEnumToJsonValue(getPricingResponsePricingPrimaryIpsInner.Type);
            writer.WriteString("type", typeRawValue);
            writer.WritePropertyName("prices");
            JsonSerializer.Serialize(writer, getPricingResponsePricingPrimaryIpsInner.Prices, jsonSerializerOptions);
        }
    }
}
