// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// GetPricingResponse
    /// </summary>
    public partial class GetPricingResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPricingResponse" /> class.
        /// </summary>
        /// <param name="pricing">pricing</param>
        [JsonConstructor]
        public GetPricingResponse(GetPricingResponsePricing pricing)
        {
            Pricing = pricing;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Pricing
        /// </summary>
        [JsonPropertyName("pricing")]
        public GetPricingResponsePricing Pricing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetPricingResponse {\n");
            sb.Append("  Pricing: ").Append(Pricing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetPricingResponse" />
    /// </summary>
    public partial class GetPricing200ResponseJsonConverter : JsonConverter<GetPricingResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GetPricing200ResponseJsonConverter" /> class.
        /// </summary>
        public GetPricing200ResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="GetPricingResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetPricingResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<GetPricingResponsePricing?> pricing = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "pricing":
                            pricing = new Option<GetPricingResponsePricing?>(JsonSerializer.Deserialize<GetPricingResponsePricing>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!pricing.IsSet)
                throw new ArgumentException("Property is required for class GetPricingResponse.", nameof(pricing));

            if (pricing.IsSet && pricing.Value == null)
                throw new ArgumentNullException(nameof(pricing), "Property is not nullable for class GetPricingResponse.");

            return new GetPricingResponse(pricing.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetPricingResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getPricingResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetPricingResponse getPricingResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getPricingResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetPricingResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getPricingResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetPricingResponse getPricingResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getPricingResponse.Pricing == null)
                throw new ArgumentNullException(nameof(getPricingResponse.Pricing), "Property is required for class GetPricingResponse.");

            writer.WritePropertyName("pricing");
            JsonSerializer.Serialize(writer, getPricingResponse.Pricing, jsonSerializerOptions);
        }
    }
}
