// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// ListDatacentersResponse
    /// </summary>
    public partial class ListDatacentersResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListDatacentersResponse" /> class.
        /// </summary>
        /// <param name="datacenters">List of [Data Centers](#tag/data-centers).</param>
        /// <param name="recommendation">This field is deprecated. Use the &#x60;recommended&#x60; flag in the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead (&#x60;server_type.locations[].recommended&#x60;).  Recommended [Data Center](#tag/data-centers) for creating new resources. </param>
        /// <param name="meta">meta</param>
        [JsonConstructor]
        public ListDatacentersResponse(List<ListDatacentersResponseDatacentersInner> datacenters, long recommendation, ListMeta meta)
        {
            Datacenters = datacenters;
            Recommendation = recommendation;
            Meta = meta;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// List of [Data Centers](#tag/data-centers).
        /// </summary>
        /// <value>List of [Data Centers](#tag/data-centers).</value>
        [JsonPropertyName("datacenters")]
        public List<ListDatacentersResponseDatacentersInner> Datacenters { get; set; }

        /// <summary>
        /// This field is deprecated. Use the &#x60;recommended&#x60; flag in the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead (&#x60;server_type.locations[].recommended&#x60;).  Recommended [Data Center](#tag/data-centers) for creating new resources. 
        /// </summary>
        /// <value>This field is deprecated. Use the &#x60;recommended&#x60; flag in the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead (&#x60;server_type.locations[].recommended&#x60;).  Recommended [Data Center](#tag/data-centers) for creating new resources. </value>
        /* <example>1</example> */
        [JsonPropertyName("recommendation")]
        [Obsolete]
        public long Recommendation { get; set; }

        /// <summary>
        /// Gets or Sets Meta
        /// </summary>
        [JsonPropertyName("meta")]
        public ListMeta Meta { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListDatacentersResponse {\n");
            sb.Append("  Datacenters: ").Append(Datacenters).Append("\n");
            sb.Append("  Recommendation: ").Append(Recommendation).Append("\n");
            sb.Append("  Meta: ").Append(Meta).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListDatacentersResponse" />
    /// </summary>
    public partial class ListDatacenters200ResponseJsonConverter : JsonConverter<ListDatacentersResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ListDatacenters200ResponseJsonConverter" /> class.
        /// </summary>
        public ListDatacenters200ResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ListDatacentersResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListDatacentersResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<ListDatacentersResponseDatacentersInner>?> datacenters = default;
            Option<long?> recommendation = default;
            Option<ListMeta?> meta = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "datacenters":
                            datacenters = new Option<List<ListDatacentersResponseDatacentersInner>?>(JsonSerializer.Deserialize<List<ListDatacentersResponseDatacentersInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "recommendation":
                            recommendation = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "meta":
                            meta = new Option<ListMeta?>(JsonSerializer.Deserialize<ListMeta>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!datacenters.IsSet)
                throw new ArgumentException("Property is required for class ListDatacentersResponse.", nameof(datacenters));

            if (!recommendation.IsSet)
                throw new ArgumentException("Property is required for class ListDatacentersResponse.", nameof(recommendation));

            if (!meta.IsSet)
                throw new ArgumentException("Property is required for class ListDatacentersResponse.", nameof(meta));

            if (datacenters.IsSet && datacenters.Value == null)
                throw new ArgumentNullException(nameof(datacenters), "Property is not nullable for class ListDatacentersResponse.");

            if (recommendation.IsSet && recommendation.Value == null)
                throw new ArgumentNullException(nameof(recommendation), "Property is not nullable for class ListDatacentersResponse.");

            if (meta.IsSet && meta.Value == null)
                throw new ArgumentNullException(nameof(meta), "Property is not nullable for class ListDatacentersResponse.");

            return new ListDatacentersResponse(datacenters.Value!, recommendation.Value!.Value!, meta.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ListDatacentersResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listDatacentersResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListDatacentersResponse listDatacentersResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, listDatacentersResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListDatacentersResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listDatacentersResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ListDatacentersResponse listDatacentersResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (listDatacentersResponse.Datacenters == null)
                throw new ArgumentNullException(nameof(listDatacentersResponse.Datacenters), "Property is required for class ListDatacentersResponse.");

            if (listDatacentersResponse.Meta == null)
                throw new ArgumentNullException(nameof(listDatacentersResponse.Meta), "Property is required for class ListDatacentersResponse.");

            writer.WritePropertyName("datacenters");
            JsonSerializer.Serialize(writer, listDatacentersResponse.Datacenters, jsonSerializerOptions);
            writer.WriteNumber("recommendation", listDatacentersResponse.Recommendation);

            writer.WritePropertyName("meta");
            JsonSerializer.Serialize(writer, listDatacentersResponse.Meta, jsonSerializerOptions);
        }
    }
}
