// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// This field is deprecated, as all of it&#39;s properties are deprecated.  [Server Types](#tag/server-types) supported and available in this [Data Center](#tag/data-centers). 
    /// </summary>
    public partial class ListDatacentersResponseDatacentersInnerServerTypes : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListDatacentersResponseDatacentersInnerServerTypes" /> class.
        /// </summary>
        /// <param name="supported">This field is deprecated. Use the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead.  List of [Server Types](#tag/server-types) supported in this [Data Center](#tag/data-centers).  These [Server Types](#tag/server-types) are generally available in this Data Center, but may be temporarily out of stock. </param>
        /// <param name="available">This field is deprecated. Use the &#x60;available&#x60; flag in the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead (&#x60;server_type.locations[].available&#x60;).  [Server Types](#tag/server-types) currently available in this [Data Center](#tag/data-centers).  These [Server Types](#tag/server-types) can currently be purchased. Types that are temporarily unavailable but are supported in this [Data Center](#tag/data-centers) are listed as &#x60;supported&#x60;. </param>
        /// <param name="availableForMigration">This field is deprecated. Use the &#x60;available&#x60; flag in the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead (&#x60;server_type.locations[].available&#x60;).  [Server Types](#tag/server-types) available to migrate to in this [Data Center](#tag/data-centers).  Existing [Servers](#tag/servers) can be migrated to these [Server Types](#tag/server-types). </param>
        [JsonConstructor]
        public ListDatacentersResponseDatacentersInnerServerTypes(List<long> supported, List<long> available, List<long> availableForMigration)
        {
            Supported = supported;
            Available = available;
            AvailableForMigration = availableForMigration;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// This field is deprecated. Use the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead.  List of [Server Types](#tag/server-types) supported in this [Data Center](#tag/data-centers).  These [Server Types](#tag/server-types) are generally available in this Data Center, but may be temporarily out of stock. 
        /// </summary>
        /// <value>This field is deprecated. Use the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead.  List of [Server Types](#tag/server-types) supported in this [Data Center](#tag/data-centers).  These [Server Types](#tag/server-types) are generally available in this Data Center, but may be temporarily out of stock. </value>
        /* <example>[1,2,3]</example> */
        [JsonPropertyName("supported")]
        [Obsolete]
        public List<long> Supported { get; set; }

        /// <summary>
        /// This field is deprecated. Use the &#x60;available&#x60; flag in the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead (&#x60;server_type.locations[].available&#x60;).  [Server Types](#tag/server-types) currently available in this [Data Center](#tag/data-centers).  These [Server Types](#tag/server-types) can currently be purchased. Types that are temporarily unavailable but are supported in this [Data Center](#tag/data-centers) are listed as &#x60;supported&#x60;. 
        /// </summary>
        /// <value>This field is deprecated. Use the &#x60;available&#x60; flag in the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead (&#x60;server_type.locations[].available&#x60;).  [Server Types](#tag/server-types) currently available in this [Data Center](#tag/data-centers).  These [Server Types](#tag/server-types) can currently be purchased. Types that are temporarily unavailable but are supported in this [Data Center](#tag/data-centers) are listed as &#x60;supported&#x60;. </value>
        /* <example>[1,2,3]</example> */
        [JsonPropertyName("available")]
        [Obsolete]
        public List<long> Available { get; set; }

        /// <summary>
        /// This field is deprecated. Use the &#x60;available&#x60; flag in the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead (&#x60;server_type.locations[].available&#x60;).  [Server Types](#tag/server-types) available to migrate to in this [Data Center](#tag/data-centers).  Existing [Servers](#tag/servers) can be migrated to these [Server Types](#tag/server-types). 
        /// </summary>
        /// <value>This field is deprecated. Use the &#x60;available&#x60; flag in the [Server Type](#tag/server-types) &#x60;locations&#x60; field instead (&#x60;server_type.locations[].available&#x60;).  [Server Types](#tag/server-types) available to migrate to in this [Data Center](#tag/data-centers).  Existing [Servers](#tag/servers) can be migrated to these [Server Types](#tag/server-types). </value>
        /* <example>[1,2,3]</example> */
        [JsonPropertyName("available_for_migration")]
        [Obsolete]
        public List<long> AvailableForMigration { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListDatacentersResponseDatacentersInnerServerTypes {\n");
            sb.Append("  Supported: ").Append(Supported).Append("\n");
            sb.Append("  Available: ").Append(Available).Append("\n");
            sb.Append("  AvailableForMigration: ").Append(AvailableForMigration).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListDatacentersResponseDatacentersInnerServerTypes" />
    /// </summary>
    public partial class ListDatacenters200ResponseDatacentersInnerServerTypesJsonConverter : JsonConverter<ListDatacentersResponseDatacentersInnerServerTypes>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ListDatacenters200ResponseDatacentersInnerServerTypesJsonConverter" /> class.
        /// </summary>
        public ListDatacenters200ResponseDatacentersInnerServerTypesJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ListDatacentersResponseDatacentersInnerServerTypes" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListDatacentersResponseDatacentersInnerServerTypes Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<long>?> supported = default;
            Option<List<long>?> available = default;
            Option<List<long>?> availableForMigration = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "supported":
                            supported = new Option<List<long>?>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "available":
                            available = new Option<List<long>?>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "available_for_migration":
                            availableForMigration = new Option<List<long>?>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!supported.IsSet)
                throw new ArgumentException("Property is required for class ListDatacentersResponseDatacentersInnerServerTypes.", nameof(supported));

            if (!available.IsSet)
                throw new ArgumentException("Property is required for class ListDatacentersResponseDatacentersInnerServerTypes.", nameof(available));

            if (!availableForMigration.IsSet)
                throw new ArgumentException("Property is required for class ListDatacentersResponseDatacentersInnerServerTypes.", nameof(availableForMigration));

            if (supported.IsSet && supported.Value == null)
                throw new ArgumentNullException(nameof(supported), "Property is not nullable for class ListDatacentersResponseDatacentersInnerServerTypes.");

            if (available.IsSet && available.Value == null)
                throw new ArgumentNullException(nameof(available), "Property is not nullable for class ListDatacentersResponseDatacentersInnerServerTypes.");

            if (availableForMigration.IsSet && availableForMigration.Value == null)
                throw new ArgumentNullException(nameof(availableForMigration), "Property is not nullable for class ListDatacentersResponseDatacentersInnerServerTypes.");

            return new ListDatacentersResponseDatacentersInnerServerTypes(supported.Value!, available.Value!, availableForMigration.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ListDatacentersResponseDatacentersInnerServerTypes" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listDatacentersResponseDatacentersInnerServerTypes"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListDatacentersResponseDatacentersInnerServerTypes listDatacentersResponseDatacentersInnerServerTypes, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, listDatacentersResponseDatacentersInnerServerTypes, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListDatacentersResponseDatacentersInnerServerTypes" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listDatacentersResponseDatacentersInnerServerTypes"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ListDatacentersResponseDatacentersInnerServerTypes listDatacentersResponseDatacentersInnerServerTypes, JsonSerializerOptions jsonSerializerOptions)
        {
            if (listDatacentersResponseDatacentersInnerServerTypes.Supported == null)
                throw new ArgumentNullException(nameof(listDatacentersResponseDatacentersInnerServerTypes.Supported), "Property is required for class ListDatacentersResponseDatacentersInnerServerTypes.");

            if (listDatacentersResponseDatacentersInnerServerTypes.Available == null)
                throw new ArgumentNullException(nameof(listDatacentersResponseDatacentersInnerServerTypes.Available), "Property is required for class ListDatacentersResponseDatacentersInnerServerTypes.");

            if (listDatacentersResponseDatacentersInnerServerTypes.AvailableForMigration == null)
                throw new ArgumentNullException(nameof(listDatacentersResponseDatacentersInnerServerTypes.AvailableForMigration), "Property is required for class ListDatacentersResponseDatacentersInnerServerTypes.");

            writer.WritePropertyName("supported");
            JsonSerializer.Serialize(writer, listDatacentersResponseDatacentersInnerServerTypes.Supported, jsonSerializerOptions);
            writer.WritePropertyName("available");
            JsonSerializer.Serialize(writer, listDatacentersResponseDatacentersInnerServerTypes.Available, jsonSerializerOptions);
            writer.WritePropertyName("available_for_migration");
            JsonSerializer.Serialize(writer, listDatacentersResponseDatacentersInnerServerTypes.AvailableForMigration, jsonSerializerOptions);
        }
    }
}
