// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner
    /// </summary>
    public partial class ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner" /> class.
        /// </summary>
        /// <param name="network">ID of the Network.</param>
        /// <param name="ip">IP address (v4) of this Load Balancer in this Network.</param>
        [JsonConstructor]
        public ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner(long network, string ip)
        {
            Network = network;
            Ip = ip;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// ID of the Network.
        /// </summary>
        /// <value>ID of the Network.</value>
        /* <example>4711</example> */
        [JsonPropertyName("network")]
        public long Network { get; set; }

        /// <summary>
        /// IP address (v4) of this Load Balancer in this Network.
        /// </summary>
        /// <value>IP address (v4) of this Load Balancer in this Network.</value>
        /* <example>10.0.0.2</example> */
        [JsonPropertyName("ip")]
        public string Ip { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner {\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner" />
    /// </summary>
    public partial class ListLoadBalancersResponseLoadBalancersInnerPrivateNetInnerJsonConverter : JsonConverter<ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ListLoadBalancersResponseLoadBalancersInnerPrivateNetInnerJsonConverter" /> class.
        /// </summary>
        public ListLoadBalancersResponseLoadBalancersInnerPrivateNetInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> network = default;
            Option<string?> ip = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "network":
                            network = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "ip":
                            ip = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!network.IsSet)
                throw new ArgumentException("Property is required for class ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner.", nameof(network));

            if (!ip.IsSet)
                throw new ArgumentException("Property is required for class ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner.", nameof(ip));

            if (network.IsSet && network.Value == null)
                throw new ArgumentNullException(nameof(network), "Property is not nullable for class ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner.");

            if (ip.IsSet && ip.Value == null)
                throw new ArgumentNullException(nameof(ip), "Property is not nullable for class ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner.");

            return new ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner(network.Value!.Value!, ip.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listLoadBalancersResponseLoadBalancersInnerPrivateNetInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner listLoadBalancersResponseLoadBalancersInnerPrivateNetInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, listLoadBalancersResponseLoadBalancersInnerPrivateNetInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listLoadBalancersResponseLoadBalancersInnerPrivateNetInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner listLoadBalancersResponseLoadBalancersInnerPrivateNetInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (listLoadBalancersResponseLoadBalancersInnerPrivateNetInner.Ip == null)
                throw new ArgumentNullException(nameof(listLoadBalancersResponseLoadBalancersInnerPrivateNetInner.Ip), "Property is required for class ListLoadBalancersResponseLoadBalancersInnerPrivateNetInner.");

            writer.WriteNumber("network", listLoadBalancersResponseLoadBalancersInnerPrivateNetInner.Network);

            writer.WriteString("ip", listLoadBalancersResponseLoadBalancersInnerPrivateNetInner.Ip);
        }
    }
}
