// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// ListVolumesResponseVolumesInner
    /// </summary>
    public partial class ListVolumesResponseVolumesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListVolumesResponseVolumesInner" /> class.
        /// </summary>
        /// <param name="id">ID of the [Volume](#tag/volumes).</param>
        /// <param name="created">Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).</param>
        /// <param name="name">Name of the Resource. Must be unique per Project.</param>
        /// <param name="location">location</param>
        /// <param name="size">Size in GB of the Volume.</param>
        /// <param name="linuxDevice">Device path on the file system for the Volume.</param>
        /// <param name="protection">protection</param>
        /// <param name="labels">User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#description/labels)\&quot;. </param>
        /// <param name="status">Status of the Volume.</param>
        /// <param name="server">ID of the Server the Volume is attached to, null if it is not attached at all.</param>
        /// <param name="format">Filesystem of the Volume if formatted on creation, null if not formatted on creation.</param>
        [JsonConstructor]
        public ListVolumesResponseVolumesInner(long id, DateTime created, string name, ListVolumesResponseVolumesInnerLocation location, decimal size, string linuxDevice, ListFloatingIpsResponseFloatingIpsInnerProtection protection, Dictionary<string, string> labels, StatusEnum status, long? server = default, string? format = default)
        {
            Id = id;
            Created = created;
            Name = name;
            Location = location;
            Size = size;
            LinuxDevice = linuxDevice;
            Protection = protection;
            Labels = labels;
            Status = status;
            Server = server;
            Format = format;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Status of the Volume.
        /// </summary>
        /// <value>Status of the Volume.</value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Available for value: available
            /// </summary>
            Available = 1,

            /// <summary>
            /// Enum Creating for value: creating
            /// </summary>
            Creating = 2
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("available"))
                return StatusEnum.Available;

            if (value.Equals("creating"))
                return StatusEnum.Creating;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("available"))
                return StatusEnum.Available;

            if (value.Equals("creating"))
                return StatusEnum.Creating;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Available)
                return "available";

            if (value == StatusEnum.Creating)
                return "creating";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Status of the Volume.
        /// </summary>
        /// <value>Status of the Volume.</value>
        /* <example>available</example> */
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// ID of the [Volume](#tag/volumes).
        /// </summary>
        /// <value>ID of the [Volume](#tag/volumes).</value>
        /* <example>42</example> */
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
        /// </summary>
        /// <value>Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).</value>
        /* <example>2016-01-30T23:55:00Z</example> */
        [JsonPropertyName("created")]
        public DateTime Created { get; set; }

        /// <summary>
        /// Name of the Resource. Must be unique per Project.
        /// </summary>
        /// <value>Name of the Resource. Must be unique per Project.</value>
        /* <example>my-resource</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [JsonPropertyName("location")]
        public ListVolumesResponseVolumesInnerLocation Location { get; set; }

        /// <summary>
        /// Size in GB of the Volume.
        /// </summary>
        /// <value>Size in GB of the Volume.</value>
        /* <example>42</example> */
        [JsonPropertyName("size")]
        public decimal Size { get; set; }

        /// <summary>
        /// Device path on the file system for the Volume.
        /// </summary>
        /// <value>Device path on the file system for the Volume.</value>
        /* <example>/dev/disk/by-id/scsi-0HC_Volume_4711</example> */
        [JsonPropertyName("linux_device")]
        public string LinuxDevice { get; set; }

        /// <summary>
        /// Gets or Sets Protection
        /// </summary>
        [JsonPropertyName("protection")]
        public ListFloatingIpsResponseFloatingIpsInnerProtection Protection { get; set; }

        /// <summary>
        /// User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#description/labels)\&quot;. 
        /// </summary>
        /// <value>User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#description/labels)\&quot;. </value>
        /* <example>{environment&#x3D;prod, example.com/my&#x3D;label, just-a-key&#x3D;}</example> */
        [JsonPropertyName("labels")]
        public Dictionary<string, string> Labels { get; set; }

        /// <summary>
        /// ID of the Server the Volume is attached to, null if it is not attached at all.
        /// </summary>
        /// <value>ID of the Server the Volume is attached to, null if it is not attached at all.</value>
        /* <example>12</example> */
        [JsonPropertyName("server")]
        public long? Server { get; set; }

        /// <summary>
        /// Filesystem of the Volume if formatted on creation, null if not formatted on creation.
        /// </summary>
        /// <value>Filesystem of the Volume if formatted on creation, null if not formatted on creation.</value>
        /* <example>xfs</example> */
        [JsonPropertyName("format")]
        public string? Format { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListVolumesResponseVolumesInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  LinuxDevice: ").Append(LinuxDevice).Append("\n");
            sb.Append("  Protection: ").Append(Protection).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (long) maximum
            if (this.Id > (long)9007199254740991)
            {
                yield return new ValidationResult("Invalid value for Id, must be a value less than or equal to 9007199254740991.", new [] { "Id" });
            }

            // Id (long) minimum
            if (this.Id < (long)1)
            {
                yield return new ValidationResult("Invalid value for Id, must be a value greater than or equal to 1.", new [] { "Id" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListVolumesResponseVolumesInner" />
    /// </summary>
    public partial class ListVolumesResponseVolumesInnerJsonConverter : JsonConverter<ListVolumesResponseVolumesInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ListVolumesResponseVolumesInnerJsonConverter" /> class.
        /// </summary>
        public ListVolumesResponseVolumesInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize Created
        /// </summary>
        public string CreatedFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ListVolumesResponseVolumesInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListVolumesResponseVolumesInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<DateTime?> created = default;
            Option<string?> name = default;
            Option<ListVolumesResponseVolumesInnerLocation?> location = default;
            Option<decimal?> size = default;
            Option<string?> linuxDevice = default;
            Option<ListFloatingIpsResponseFloatingIpsInnerProtection?> protection = default;
            Option<Dictionary<string, string>?> labels = default;
            Option<ListVolumesResponseVolumesInner.StatusEnum?> status = default;
            Option<long?> server = default;
            Option<string?> format = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "created":
                            created = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "location":
                            location = new Option<ListVolumesResponseVolumesInnerLocation?>(JsonSerializer.Deserialize<ListVolumesResponseVolumesInnerLocation>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "size":
                            size = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "linux_device":
                            linuxDevice = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "protection":
                            protection = new Option<ListFloatingIpsResponseFloatingIpsInnerProtection?>(JsonSerializer.Deserialize<ListFloatingIpsResponseFloatingIpsInnerProtection>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "labels":
                            labels = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<ListVolumesResponseVolumesInner.StatusEnum?>(ListVolumesResponseVolumesInner.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "server":
                            server = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "format":
                            format = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(id));

            if (!created.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(created));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(name));

            if (!location.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(location));

            if (!size.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(size));

            if (!linuxDevice.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(linuxDevice));

            if (!protection.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(protection));

            if (!labels.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(labels));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(status));

            if (!server.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(server));

            if (!format.IsSet)
                throw new ArgumentException("Property is required for class ListVolumesResponseVolumesInner.", nameof(format));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ListVolumesResponseVolumesInner.");

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class ListVolumesResponseVolumesInner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ListVolumesResponseVolumesInner.");

            if (location.IsSet && location.Value == null)
                throw new ArgumentNullException(nameof(location), "Property is not nullable for class ListVolumesResponseVolumesInner.");

            if (size.IsSet && size.Value == null)
                throw new ArgumentNullException(nameof(size), "Property is not nullable for class ListVolumesResponseVolumesInner.");

            if (linuxDevice.IsSet && linuxDevice.Value == null)
                throw new ArgumentNullException(nameof(linuxDevice), "Property is not nullable for class ListVolumesResponseVolumesInner.");

            if (protection.IsSet && protection.Value == null)
                throw new ArgumentNullException(nameof(protection), "Property is not nullable for class ListVolumesResponseVolumesInner.");

            if (labels.IsSet && labels.Value == null)
                throw new ArgumentNullException(nameof(labels), "Property is not nullable for class ListVolumesResponseVolumesInner.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class ListVolumesResponseVolumesInner.");

            return new ListVolumesResponseVolumesInner(id.Value!.Value!, created.Value!.Value!, name.Value!, location.Value!, size.Value!.Value!, linuxDevice.Value!, protection.Value!, labels.Value!, status.Value!.Value!, server.Value!, format.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ListVolumesResponseVolumesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listVolumesResponseVolumesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListVolumesResponseVolumesInner listVolumesResponseVolumesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, listVolumesResponseVolumesInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListVolumesResponseVolumesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listVolumesResponseVolumesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ListVolumesResponseVolumesInner listVolumesResponseVolumesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (listVolumesResponseVolumesInner.Name == null)
                throw new ArgumentNullException(nameof(listVolumesResponseVolumesInner.Name), "Property is required for class ListVolumesResponseVolumesInner.");

            if (listVolumesResponseVolumesInner.Location == null)
                throw new ArgumentNullException(nameof(listVolumesResponseVolumesInner.Location), "Property is required for class ListVolumesResponseVolumesInner.");

            if (listVolumesResponseVolumesInner.LinuxDevice == null)
                throw new ArgumentNullException(nameof(listVolumesResponseVolumesInner.LinuxDevice), "Property is required for class ListVolumesResponseVolumesInner.");

            if (listVolumesResponseVolumesInner.Protection == null)
                throw new ArgumentNullException(nameof(listVolumesResponseVolumesInner.Protection), "Property is required for class ListVolumesResponseVolumesInner.");

            if (listVolumesResponseVolumesInner.Labels == null)
                throw new ArgumentNullException(nameof(listVolumesResponseVolumesInner.Labels), "Property is required for class ListVolumesResponseVolumesInner.");

            writer.WriteNumber("id", listVolumesResponseVolumesInner.Id);

            writer.WriteString("created", listVolumesResponseVolumesInner.Created.ToString(CreatedFormat));

            writer.WriteString("name", listVolumesResponseVolumesInner.Name);

            writer.WritePropertyName("location");
            JsonSerializer.Serialize(writer, listVolumesResponseVolumesInner.Location, jsonSerializerOptions);
            writer.WriteNumber("size", listVolumesResponseVolumesInner.Size);

            writer.WriteString("linux_device", listVolumesResponseVolumesInner.LinuxDevice);

            writer.WritePropertyName("protection");
            JsonSerializer.Serialize(writer, listVolumesResponseVolumesInner.Protection, jsonSerializerOptions);
            writer.WritePropertyName("labels");
            JsonSerializer.Serialize(writer, listVolumesResponseVolumesInner.Labels, jsonSerializerOptions);
            var statusRawValue = ListVolumesResponseVolumesInner.StatusEnumToJsonValue(listVolumesResponseVolumesInner.Status);
            writer.WriteString("status", statusRawValue);
            if (listVolumesResponseVolumesInner.Server != null)
                writer.WriteNumber("server", listVolumesResponseVolumesInner.Server.Value);
            else
                writer.WriteNull("server");

            if (listVolumesResponseVolumesInner.Format != null)
                writer.WriteString("format", listVolumesResponseVolumesInner.Format);
            else
                writer.WriteNull("format");
        }
    }
}
