// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// Information about the Server the Image was created from.
    /// </summary>
    public partial class ListImagesResponseImagesInnerCreatedFrom : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListImagesResponseImagesInnerCreatedFrom" /> class.
        /// </summary>
        /// <param name="id">ID of the Server the Image was created from.</param>
        /// <param name="name">Server name at the time the Image was created.</param>
        [JsonConstructor]
        public ListImagesResponseImagesInnerCreatedFrom(long id, string name)
        {
            Id = id;
            Name = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// ID of the Server the Image was created from.
        /// </summary>
        /// <value>ID of the Server the Image was created from.</value>
        /* <example>1</example> */
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Server name at the time the Image was created.
        /// </summary>
        /// <value>Server name at the time the Image was created.</value>
        /* <example>Server</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListImagesResponseImagesInnerCreatedFrom {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListImagesResponseImagesInnerCreatedFrom" />
    /// </summary>
    public partial class ListImages200ResponseImagesInnerCreatedFromJsonConverter : JsonConverter<ListImagesResponseImagesInnerCreatedFrom>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ListImages200ResponseImagesInnerCreatedFromJsonConverter" /> class.
        /// </summary>
        public ListImages200ResponseImagesInnerCreatedFromJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ListImagesResponseImagesInnerCreatedFrom" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListImagesResponseImagesInnerCreatedFrom Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ListImagesResponseImagesInnerCreatedFrom.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ListImagesResponseImagesInnerCreatedFrom.", nameof(name));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ListImagesResponseImagesInnerCreatedFrom.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ListImagesResponseImagesInnerCreatedFrom.");

            return new ListImagesResponseImagesInnerCreatedFrom(id.Value!.Value!, name.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ListImagesResponseImagesInnerCreatedFrom" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listImagesResponseImagesInnerCreatedFrom"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListImagesResponseImagesInnerCreatedFrom listImagesResponseImagesInnerCreatedFrom, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, listImagesResponseImagesInnerCreatedFrom, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListImagesResponseImagesInnerCreatedFrom" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listImagesResponseImagesInnerCreatedFrom"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ListImagesResponseImagesInnerCreatedFrom listImagesResponseImagesInnerCreatedFrom, JsonSerializerOptions jsonSerializerOptions)
        {
            if (listImagesResponseImagesInnerCreatedFrom.Name == null)
                throw new ArgumentNullException(nameof(listImagesResponseImagesInnerCreatedFrom.Name), "Property is required for class ListImagesResponseImagesInnerCreatedFrom.");

            writer.WriteNumber("id", listImagesResponseImagesInnerCreatedFrom.Id);

            writer.WriteString("name", listImagesResponseImagesInnerCreatedFrom.Name);
        }
    }
}
