// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// Protection configuration for the Resource.
    /// </summary>
    public partial class ListFloatingIpsResponseFloatingIpsInnerProtection : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListFloatingIpsResponseFloatingIpsInnerProtection" /> class.
        /// </summary>
        /// <param name="delete">Prevent the Resource from being deleted.</param>
        [JsonConstructor]
        public ListFloatingIpsResponseFloatingIpsInnerProtection(bool delete)
        {
            Delete = delete;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Prevent the Resource from being deleted.
        /// </summary>
        /// <value>Prevent the Resource from being deleted.</value>
        /* <example>false</example> */
        [JsonPropertyName("delete")]
        public bool Delete { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListFloatingIpsResponseFloatingIpsInnerProtection {\n");
            sb.Append("  Delete: ").Append(Delete).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListFloatingIpsResponseFloatingIpsInnerProtection" />
    /// </summary>
    public partial class ListFloatingIpsResponseFloatingIpsInnerProtectionJsonConverter : JsonConverter<ListFloatingIpsResponseFloatingIpsInnerProtection>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ListFloatingIpsResponseFloatingIpsInnerProtectionJsonConverter" /> class.
        /// </summary>
        public ListFloatingIpsResponseFloatingIpsInnerProtectionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ListFloatingIpsResponseFloatingIpsInnerProtection" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListFloatingIpsResponseFloatingIpsInnerProtection Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> delete = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "delete":
                            delete = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!delete.IsSet)
                throw new ArgumentException("Property is required for class ListFloatingIpsResponseFloatingIpsInnerProtection.", nameof(delete));

            if (delete.IsSet && delete.Value == null)
                throw new ArgumentNullException(nameof(delete), "Property is not nullable for class ListFloatingIpsResponseFloatingIpsInnerProtection.");

            return new ListFloatingIpsResponseFloatingIpsInnerProtection(delete.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ListFloatingIpsResponseFloatingIpsInnerProtection" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listFloatingIpsResponseFloatingIpsInnerProtection"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListFloatingIpsResponseFloatingIpsInnerProtection listFloatingIpsResponseFloatingIpsInnerProtection, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, listFloatingIpsResponseFloatingIpsInnerProtection, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListFloatingIpsResponseFloatingIpsInnerProtection" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listFloatingIpsResponseFloatingIpsInnerProtection"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ListFloatingIpsResponseFloatingIpsInnerProtection listFloatingIpsResponseFloatingIpsInnerProtection, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("delete", listFloatingIpsResponseFloatingIpsInnerProtection.Delete);
        }
    }
}
