// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// LoadBalancerService
    /// </summary>
    public partial class LoadBalancerService : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoadBalancerService" /> class.
        /// </summary>
        /// <param name="loadBalancerServiceTCP"></param>
        public LoadBalancerService(LoadBalancerServiceTCP loadBalancerServiceTCP)
        {
            LoadBalancerServiceTCP = loadBalancerServiceTCP;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadBalancerService" /> class.
        /// </summary>
        /// <param name="loadBalancerServiceHTTPProtocol"></param>
        public LoadBalancerService(LoadBalancerServiceHTTPProtocol loadBalancerServiceHTTPProtocol)
        {
            LoadBalancerServiceHTTPProtocol = loadBalancerServiceHTTPProtocol;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadBalancerService" /> class.
        /// </summary>
        /// <param name="loadBalancerServiceHTTPSProtocol"></param>
        public LoadBalancerService(LoadBalancerServiceHTTPSProtocol loadBalancerServiceHTTPSProtocol)
        {
            LoadBalancerServiceHTTPSProtocol = loadBalancerServiceHTTPSProtocol;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Protocol
        /// </summary>
        public enum ProtocolEnum
        {
            /// <summary>
            /// Enum Https for value: https
            /// </summary>
            Https = 1
        }

        /// <summary>
        /// Returns a <see cref="ProtocolEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ProtocolEnum ProtocolEnumFromString(string value)
        {
            if (value.Equals("https"))
                return ProtocolEnum.Https;

            throw new NotImplementedException($"Could not convert value to type ProtocolEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ProtocolEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ProtocolEnum? ProtocolEnumFromStringOrDefault(string value)
        {
            if (value.Equals("https"))
                return ProtocolEnum.Https;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ProtocolEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ProtocolEnumToJsonValue(ProtocolEnum value)
        {
            if (value == ProtocolEnum.Https)
                return "https";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets LoadBalancerServiceTCP
        /// </summary>
        public LoadBalancerServiceTCP? LoadBalancerServiceTCP { get; set; }

        /// <summary>
        /// Gets or Sets LoadBalancerServiceHTTPProtocol
        /// </summary>
        public LoadBalancerServiceHTTPProtocol? LoadBalancerServiceHTTPProtocol { get; set; }

        /// <summary>
        /// Gets or Sets LoadBalancerServiceHTTPSProtocol
        /// </summary>
        public LoadBalancerServiceHTTPSProtocol? LoadBalancerServiceHTTPSProtocol { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoadBalancerService {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LoadBalancerService" />
    /// </summary>
    public partial class LoadBalancerServiceJsonConverter : JsonConverter<LoadBalancerService>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadBalancerServiceJsonConverter" /> class.
        /// </summary>
        public LoadBalancerServiceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="LoadBalancerService" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LoadBalancerService Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<LoadBalancerService.ProtocolEnum?> protocol = default;

            ServiceHTTPProtocol? serviceHTTPProtocol = null;
            ServiceHTTPSProtocol? serviceHTTPSProtocol = null;
            ServiceTCP? serviceTCP = null;
            LoadBalancerServiceHTTPProtocol? loadBalancerServiceHTTPProtocol = null;
            LoadBalancerServiceHTTPSProtocol? loadBalancerServiceHTTPSProtocol = null;
            LoadBalancerServiceTCP? loadBalancerServiceTCP = null;

            Utf8JsonReader utf8JsonReaderDiscriminator = utf8JsonReader;
            while (utf8JsonReaderDiscriminator.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderDiscriminator.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderDiscriminator.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderDiscriminator.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderDiscriminator.CurrentDepth)
                    break;

                if (utf8JsonReaderDiscriminator.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderDiscriminator.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReaderDiscriminator.GetString();
                    utf8JsonReaderDiscriminator.Read();
                    if (localVarJsonPropertyName?.Equals("protocol") ?? false)
                    {
                        string? discriminator = utf8JsonReaderDiscriminator.GetString();
                        if (discriminator?.Equals("http") ?? false)
                        {
                            Utf8JsonReader utf8JsonReaderServiceHTTPProtocol = utf8JsonReader;
                            serviceHTTPProtocol = JsonSerializer.Deserialize<ServiceHTTPProtocol>(ref utf8JsonReaderServiceHTTPProtocol, jsonSerializerOptions);
                        }
                        if (discriminator?.Equals("https") ?? false)
                        {
                            Utf8JsonReader utf8JsonReaderServiceHTTPSProtocol = utf8JsonReader;
                            serviceHTTPSProtocol = JsonSerializer.Deserialize<ServiceHTTPSProtocol>(ref utf8JsonReaderServiceHTTPSProtocol, jsonSerializerOptions);
                        }
                        if (discriminator?.Equals("tcp") ?? false)
                        {
                            Utf8JsonReader utf8JsonReaderServiceTCP = utf8JsonReader;
                            serviceTCP = JsonSerializer.Deserialize<ServiceTCP>(ref utf8JsonReaderServiceTCP, jsonSerializerOptions);
                        }
                        if (discriminator?.Equals("LoadBalancerServiceHTTPProtocol") ?? false)
                        {
                            Utf8JsonReader utf8JsonReaderLoadBalancerServiceHTTPProtocol = utf8JsonReader;
                            loadBalancerServiceHTTPProtocol = JsonSerializer.Deserialize<LoadBalancerServiceHTTPProtocol>(ref utf8JsonReaderLoadBalancerServiceHTTPProtocol, jsonSerializerOptions);
                        }
                        if (discriminator?.Equals("LoadBalancerServiceHTTPSProtocol") ?? false)
                        {
                            Utf8JsonReader utf8JsonReaderLoadBalancerServiceHTTPSProtocol = utf8JsonReader;
                            loadBalancerServiceHTTPSProtocol = JsonSerializer.Deserialize<LoadBalancerServiceHTTPSProtocol>(ref utf8JsonReaderLoadBalancerServiceHTTPSProtocol, jsonSerializerOptions);
                        }
                        if (discriminator?.Equals("LoadBalancerServiceTCP") ?? false)
                        {
                            Utf8JsonReader utf8JsonReaderLoadBalancerServiceTCP = utf8JsonReader;
                            loadBalancerServiceTCP = JsonSerializer.Deserialize<LoadBalancerServiceTCP>(ref utf8JsonReaderLoadBalancerServiceTCP, jsonSerializerOptions);
                        }
                    }
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "protocol":
                            string? protocolRawValue = utf8JsonReader.GetString();
                            if (protocolRawValue != null)
                                protocol = new Option<LoadBalancerService.ProtocolEnum?>(LoadBalancerService.ProtocolEnumFromStringOrDefault(protocolRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!protocol.IsSet)
                throw new ArgumentException("Property is required for class LoadBalancerService.", nameof(protocol));

            if (protocol.IsSet && protocol.Value == null)
                throw new ArgumentNullException(nameof(protocol), "Property is not nullable for class LoadBalancerService.");

            if (loadBalancerServiceHTTPProtocol != null)
                return new LoadBalancerService(loadBalancerServiceHTTPProtocol);

            if (loadBalancerServiceHTTPSProtocol != null)
                return new LoadBalancerService(loadBalancerServiceHTTPSProtocol);

            if (loadBalancerServiceTCP != null)
                return new LoadBalancerService(loadBalancerServiceTCP);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="LoadBalancerService" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loadBalancerService"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LoadBalancerService loadBalancerService, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            if (loadBalancerService.LoadBalancerServiceTCP != null)
            {
                LoadBalancerServiceTCPJsonConverter loadBalancerServiceTCPJsonConverter = (LoadBalancerServiceTCPJsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(loadBalancerService.LoadBalancerServiceTCP.GetType()));
                loadBalancerServiceTCPJsonConverter.WriteProperties(writer, loadBalancerService.LoadBalancerServiceTCP, jsonSerializerOptions);
            }

            if (loadBalancerService.LoadBalancerServiceHTTPProtocol != null)
            {
                LoadBalancerServiceHTTPProtocolJsonConverter loadBalancerServiceHTTPProtocolJsonConverter = (LoadBalancerServiceHTTPProtocolJsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(loadBalancerService.LoadBalancerServiceHTTPProtocol.GetType()));
                loadBalancerServiceHTTPProtocolJsonConverter.WriteProperties(writer, loadBalancerService.LoadBalancerServiceHTTPProtocol, jsonSerializerOptions);
            }

            if (loadBalancerService.LoadBalancerServiceHTTPSProtocol != null)
            {
                LoadBalancerServiceHTTPSProtocolJsonConverter loadBalancerServiceHTTPSProtocolJsonConverter = (LoadBalancerServiceHTTPSProtocolJsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(loadBalancerService.LoadBalancerServiceHTTPSProtocol.GetType()));
                loadBalancerServiceHTTPSProtocolJsonConverter.WriteProperties(writer, loadBalancerService.LoadBalancerServiceHTTPSProtocol, jsonSerializerOptions);
            }

            WriteProperties(writer, loadBalancerService, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LoadBalancerService" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loadBalancerService"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LoadBalancerService loadBalancerService, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
