// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// Label selector used to determine targets. Only present for target type \&quot;label_selector\&quot;.
    /// </summary>
    public partial class LoadBalancerTargetLabelSelector : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoadBalancerTargetLabelSelector" /> class.
        /// </summary>
        /// <param name="selector">Label selector.</param>
        [JsonConstructor]
        public LoadBalancerTargetLabelSelector(string selector)
        {
            Selector = selector;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Label selector.
        /// </summary>
        /// <value>Label selector.</value>
        /* <example>env&#x3D;prod</example> */
        [JsonPropertyName("selector")]
        public string Selector { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoadBalancerTargetLabelSelector {\n");
            sb.Append("  Selector: ").Append(Selector).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Selector (string) maxLength
            if (this.Selector != null && this.Selector.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for Selector, length must be less than 1000.", new [] { "Selector" });
            }

            // Selector (string) minLength
            if (this.Selector != null && this.Selector.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Selector, length must be greater than 1.", new [] { "Selector" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LoadBalancerTargetLabelSelector" />
    /// </summary>
    public partial class LoadBalancerTargetLabelSelectorJsonConverter : JsonConverter<LoadBalancerTargetLabelSelector>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadBalancerTargetLabelSelectorJsonConverter" /> class.
        /// </summary>
        public LoadBalancerTargetLabelSelectorJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="LoadBalancerTargetLabelSelector" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LoadBalancerTargetLabelSelector Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> selector = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "selector":
                            selector = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!selector.IsSet)
                throw new ArgumentException("Property is required for class LoadBalancerTargetLabelSelector.", nameof(selector));

            if (selector.IsSet && selector.Value == null)
                throw new ArgumentNullException(nameof(selector), "Property is not nullable for class LoadBalancerTargetLabelSelector.");

            return new LoadBalancerTargetLabelSelector(selector.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="LoadBalancerTargetLabelSelector" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loadBalancerTargetLabelSelector"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LoadBalancerTargetLabelSelector loadBalancerTargetLabelSelector, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, loadBalancerTargetLabelSelector, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LoadBalancerTargetLabelSelector" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loadBalancerTargetLabelSelector"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LoadBalancerTargetLabelSelector loadBalancerTargetLabelSelector, JsonSerializerOptions jsonSerializerOptions)
        {
            if (loadBalancerTargetLabelSelector.Selector == null)
                throw new ArgumentNullException(nameof(loadBalancerTargetLabelSelector.Selector), "Property is required for class LoadBalancerTargetLabelSelector.");

            writer.WriteString("selector", loadBalancerTargetLabelSelector.Selector);
        }
    }
}
