// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// PlacementGroupsResponse
    /// </summary>
    public partial class PlacementGroupsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlacementGroupsResponse" /> class.
        /// </summary>
        /// <param name="placementGroups">placementGroups</param>
        /// <param name="meta">meta</param>
        [JsonConstructor]
        public PlacementGroupsResponse(List<PlacementGroup> placementGroups, ListMeta meta)
        {
            PlacementGroups = placementGroups;
            Meta = meta;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets PlacementGroups
        /// </summary>
        [JsonPropertyName("placement_groups")]
        public List<PlacementGroup> PlacementGroups { get; set; }

        /// <summary>
        /// Gets or Sets Meta
        /// </summary>
        [JsonPropertyName("meta")]
        public ListMeta Meta { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlacementGroupsResponse {\n");
            sb.Append("  PlacementGroups: ").Append(PlacementGroups).Append("\n");
            sb.Append("  Meta: ").Append(Meta).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PlacementGroupsResponse" />
    /// </summary>
    public partial class PlacementGroupsResponseJsonConverter : JsonConverter<PlacementGroupsResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PlacementGroupsResponseJsonConverter" /> class.
        /// </summary>
        public PlacementGroupsResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="PlacementGroupsResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PlacementGroupsResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<PlacementGroup>?> placementGroups = default;
            Option<ListMeta?> meta = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "placement_groups":
                            placementGroups = new Option<List<PlacementGroup>?>(JsonSerializer.Deserialize<List<PlacementGroup>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "meta":
                            meta = new Option<ListMeta?>(JsonSerializer.Deserialize<ListMeta>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!placementGroups.IsSet)
                throw new ArgumentException("Property is required for class PlacementGroupsResponse.", nameof(placementGroups));

            if (!meta.IsSet)
                throw new ArgumentException("Property is required for class PlacementGroupsResponse.", nameof(meta));

            if (placementGroups.IsSet && placementGroups.Value == null)
                throw new ArgumentNullException(nameof(placementGroups), "Property is not nullable for class PlacementGroupsResponse.");

            if (meta.IsSet && meta.Value == null)
                throw new ArgumentNullException(nameof(meta), "Property is not nullable for class PlacementGroupsResponse.");

            return new PlacementGroupsResponse(placementGroups.Value!, meta.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PlacementGroupsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="placementGroupsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PlacementGroupsResponse placementGroupsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, placementGroupsResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PlacementGroupsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="placementGroupsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PlacementGroupsResponse placementGroupsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (placementGroupsResponse.PlacementGroups == null)
                throw new ArgumentNullException(nameof(placementGroupsResponse.PlacementGroups), "Property is required for class PlacementGroupsResponse.");

            if (placementGroupsResponse.Meta == null)
                throw new ArgumentNullException(nameof(placementGroupsResponse.Meta), "Property is required for class PlacementGroupsResponse.");

            writer.WritePropertyName("placement_groups");
            JsonSerializer.Serialize(writer, placementGroupsResponse.PlacementGroups, jsonSerializerOptions);
            writer.WritePropertyName("meta");
            JsonSerializer.Serialize(writer, placementGroupsResponse.Meta, jsonSerializerOptions);
        }
    }
}
