// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// RequestServerConsoleResponse
    /// </summary>
    public partial class RequestServerConsoleResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestServerConsoleResponse" /> class.
        /// </summary>
        /// <param name="wssUrl">URL of websocket proxy to use; this includes a token which is valid for a limited time only.</param>
        /// <param name="password">VNC password to use for this connection (this password only works in combination with a wss_url with valid token).</param>
        /// <param name="action">action</param>
        [JsonConstructor]
        public RequestServerConsoleResponse(string wssUrl, string password, Action action)
        {
            WssUrl = wssUrl;
            Password = password;
            Action = action;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// URL of websocket proxy to use; this includes a token which is valid for a limited time only.
        /// </summary>
        /// <value>URL of websocket proxy to use; this includes a token which is valid for a limited time only.</value>
        /* <example>wss://console.hetzner.cloud/?server_id&#x3D;1&amp;token&#x3D;3db32d15-af2f-459c-8bf8-dee1fd05f49c</example> */
        [JsonPropertyName("wss_url")]
        public string WssUrl { get; set; }

        /// <summary>
        /// VNC password to use for this connection (this password only works in combination with a wss_url with valid token).
        /// </summary>
        /// <value>VNC password to use for this connection (this password only works in combination with a wss_url with valid token).</value>
        /* <example>9MQaTg2VAGI0FIpc10k3UpRXcHj2wQ6x</example> */
        [JsonPropertyName("password")]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [JsonPropertyName("action")]
        public Action Action { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequestServerConsoleResponse {\n");
            sb.Append("  WssUrl: ").Append(WssUrl).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RequestServerConsoleResponse" />
    /// </summary>
    public partial class RequestServerConsole201ResponseJsonConverter : JsonConverter<RequestServerConsoleResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestServerConsole201ResponseJsonConverter" /> class.
        /// </summary>
        public RequestServerConsole201ResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="RequestServerConsoleResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RequestServerConsoleResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> wssUrl = default;
            Option<string?> password = default;
            Option<Action?> action = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "wss_url":
                            wssUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "password":
                            password = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action":
                            action = new Option<Action?>(JsonSerializer.Deserialize<Action>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!wssUrl.IsSet)
                throw new ArgumentException("Property is required for class RequestServerConsoleResponse.", nameof(wssUrl));

            if (!password.IsSet)
                throw new ArgumentException("Property is required for class RequestServerConsoleResponse.", nameof(password));

            if (!action.IsSet)
                throw new ArgumentException("Property is required for class RequestServerConsoleResponse.", nameof(action));

            if (wssUrl.IsSet && wssUrl.Value == null)
                throw new ArgumentNullException(nameof(wssUrl), "Property is not nullable for class RequestServerConsoleResponse.");

            if (password.IsSet && password.Value == null)
                throw new ArgumentNullException(nameof(password), "Property is not nullable for class RequestServerConsoleResponse.");

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class RequestServerConsoleResponse.");

            return new RequestServerConsoleResponse(wssUrl.Value!, password.Value!, action.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RequestServerConsoleResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="requestServerConsoleResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RequestServerConsoleResponse requestServerConsoleResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, requestServerConsoleResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RequestServerConsoleResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="requestServerConsoleResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RequestServerConsoleResponse requestServerConsoleResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (requestServerConsoleResponse.WssUrl == null)
                throw new ArgumentNullException(nameof(requestServerConsoleResponse.WssUrl), "Property is required for class RequestServerConsoleResponse.");

            if (requestServerConsoleResponse.Password == null)
                throw new ArgumentNullException(nameof(requestServerConsoleResponse.Password), "Property is required for class RequestServerConsoleResponse.");

            if (requestServerConsoleResponse.Action == null)
                throw new ArgumentNullException(nameof(requestServerConsoleResponse.Action), "Property is required for class RequestServerConsoleResponse.");

            writer.WriteString("wss_url", requestServerConsoleResponse.WssUrl);

            writer.WriteString("password", requestServerConsoleResponse.Password);

            writer.WritePropertyName("action");
            JsonSerializer.Serialize(writer, requestServerConsoleResponse.Action, jsonSerializerOptions);
        }
    }
}
