// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * # This is the .NET Library for the Hetzner Cloud API. 
 * The version of the OpenAPI document: 1.0.0
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// SetZoneRrsetRecordsRequest
    /// </summary>
    public partial class SetZoneRrsetRecordsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetZoneRrsetRecordsRequest" /> class.
        /// </summary>
        /// <param name="records">Records to set in the [RRSet](#tag/zone-rrsets).  Must not be empty and must only contain distinct record values. </param>
        [JsonConstructor]
        public SetZoneRrsetRecordsRequest(List<Record> records)
        {
            Records = records;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Records to set in the [RRSet](#tag/zone-rrsets).  Must not be empty and must only contain distinct record values. 
        /// </summary>
        /// <value>Records to set in the [RRSet](#tag/zone-rrsets).  Must not be empty and must only contain distinct record values. </value>
        [JsonPropertyName("records")]
        public List<Record> Records { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetZoneRrsetRecordsRequest {\n");
            sb.Append("  Records: ").Append(Records).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SetZoneRrsetRecordsRequest" />
    /// </summary>
    public partial class SetZoneRrsetRecordsRequestJsonConverter : JsonConverter<SetZoneRrsetRecordsRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SetZoneRrsetRecordsRequestJsonConverter" /> class.
        /// </summary>
        public SetZoneRrsetRecordsRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SetZoneRrsetRecordsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SetZoneRrsetRecordsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<Record>?> records = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "records":
                            records = new Option<List<Record>?>(JsonSerializer.Deserialize<List<Record>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!records.IsSet)
                throw new ArgumentException("Property is required for class SetZoneRrsetRecordsRequest.", nameof(records));

            if (records.IsSet && records.Value == null)
                throw new ArgumentNullException(nameof(records), "Property is not nullable for class SetZoneRrsetRecordsRequest.");

            return new SetZoneRrsetRecordsRequest(records.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SetZoneRrsetRecordsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="setZoneRrsetRecordsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SetZoneRrsetRecordsRequest setZoneRrsetRecordsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, setZoneRrsetRecordsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SetZoneRrsetRecordsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="setZoneRrsetRecordsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SetZoneRrsetRecordsRequest setZoneRrsetRecordsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (setZoneRrsetRecordsRequest.Records == null)
                throw new ArgumentNullException(nameof(setZoneRrsetRecordsRequest.Records), "Property is required for class SetZoneRrsetRecordsRequest.");

            writer.WritePropertyName("records");
            JsonSerializer.Serialize(writer, setZoneRrsetRecordsRequest.Records, jsonSerializerOptions);
        }
    }
}
