// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// ZonePrimaryAllOfAuthoritativeNameservers
    /// </summary>
    public partial class ZonePrimaryAllOfAuthoritativeNameservers : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ZonePrimaryAllOfAuthoritativeNameservers" /> class.
        /// </summary>
        /// <param name="assigned">Authoritative Hetzner nameservers assigned to this [Zone](#tag/zones). </param>
        /// <param name="delegated">Authoritative nameservers currently delegated to by the parent DNS zone.  If these don&#39;t match the assigned authoritative nameservers, the DNS zone is currently not being served by Hetzner. </param>
        /// <param name="delegationLastCheck">Point in time (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format) when the DNS zone delegation was last checked. </param>
        /// <param name="delegationStatus">Status of the delegation. </param>
        [JsonConstructor]
        public ZonePrimaryAllOfAuthoritativeNameservers(List<string> assigned, List<string> delegated, DateTime? delegationLastCheck = default, Option<DelegationStatusEnum?> delegationStatus = default)
        {
            Assigned = assigned;
            Delegated = delegated;
            DelegationLastCheck = delegationLastCheck;
            DelegationStatusOption = delegationStatus;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Status of the delegation. 
        /// </summary>
        /// <value>Status of the delegation. </value>
        public enum DelegationStatusEnum
        {
            /// <summary>
            /// Enum Valid for value: valid
            /// </summary>
            Valid = 1,

            /// <summary>
            /// Enum PartiallyValid for value: partially-valid
            /// </summary>
            PartiallyValid = 2,

            /// <summary>
            /// Enum Invalid for value: invalid
            /// </summary>
            Invalid = 3,

            /// <summary>
            /// Enum Lame for value: lame
            /// </summary>
            Lame = 4,

            /// <summary>
            /// Enum Unregistered for value: unregistered
            /// </summary>
            Unregistered = 5,

            /// <summary>
            /// Enum Unknown for value: unknown
            /// </summary>
            Unknown = 6
        }

        /// <summary>
        /// Returns a <see cref="DelegationStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static DelegationStatusEnum DelegationStatusEnumFromString(string value)
        {
            if (value.Equals("valid"))
                return DelegationStatusEnum.Valid;

            if (value.Equals("partially-valid"))
                return DelegationStatusEnum.PartiallyValid;

            if (value.Equals("invalid"))
                return DelegationStatusEnum.Invalid;

            if (value.Equals("lame"))
                return DelegationStatusEnum.Lame;

            if (value.Equals("unregistered"))
                return DelegationStatusEnum.Unregistered;

            if (value.Equals("unknown"))
                return DelegationStatusEnum.Unknown;

            throw new NotImplementedException($"Could not convert value to type DelegationStatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="DelegationStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static DelegationStatusEnum? DelegationStatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("valid"))
                return DelegationStatusEnum.Valid;

            if (value.Equals("partially-valid"))
                return DelegationStatusEnum.PartiallyValid;

            if (value.Equals("invalid"))
                return DelegationStatusEnum.Invalid;

            if (value.Equals("lame"))
                return DelegationStatusEnum.Lame;

            if (value.Equals("unregistered"))
                return DelegationStatusEnum.Unregistered;

            if (value.Equals("unknown"))
                return DelegationStatusEnum.Unknown;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="DelegationStatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string DelegationStatusEnumToJsonValue(DelegationStatusEnum? value)
        {
            if (value == DelegationStatusEnum.Valid)
                return "valid";

            if (value == DelegationStatusEnum.PartiallyValid)
                return "partially-valid";

            if (value == DelegationStatusEnum.Invalid)
                return "invalid";

            if (value == DelegationStatusEnum.Lame)
                return "lame";

            if (value == DelegationStatusEnum.Unregistered)
                return "unregistered";

            if (value == DelegationStatusEnum.Unknown)
                return "unknown";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of DelegationStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DelegationStatusEnum?> DelegationStatusOption { get; private set; }

        /// <summary>
        /// Status of the delegation. 
        /// </summary>
        /// <value>Status of the delegation. </value>
        [JsonPropertyName("delegation_status")]
        public DelegationStatusEnum? DelegationStatus { get { return this.DelegationStatusOption.Value; } set { this.DelegationStatusOption = new(value); } }

        /// <summary>
        /// Authoritative Hetzner nameservers assigned to this [Zone](#tag/zones). 
        /// </summary>
        /// <value>Authoritative Hetzner nameservers assigned to this [Zone](#tag/zones). </value>
        /* <example>[hydrogen.ns.hetzner.com., oxygen.ns.hetzner.com., helium.ns.hetzner.de.]</example> */
        [JsonPropertyName("assigned")]
        public List<string> Assigned { get; set; }

        /// <summary>
        /// Authoritative nameservers currently delegated to by the parent DNS zone.  If these don&#39;t match the assigned authoritative nameservers, the DNS zone is currently not being served by Hetzner. 
        /// </summary>
        /// <value>Authoritative nameservers currently delegated to by the parent DNS zone.  If these don&#39;t match the assigned authoritative nameservers, the DNS zone is currently not being served by Hetzner. </value>
        /* <example>[hydrogen.ns.hetzner.com., oxygen.ns.hetzner.com., helium.ns.hetzner.de.]</example> */
        [JsonPropertyName("delegated")]
        public List<string> Delegated { get; set; }

        /// <summary>
        /// Point in time (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format) when the DNS zone delegation was last checked. 
        /// </summary>
        /// <value>Point in time (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format) when the DNS zone delegation was last checked. </value>
        /* <example>2016-01-30T23:55:00Z</example> */
        [JsonPropertyName("delegation_last_check")]
        public DateTime? DelegationLastCheck { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ZonePrimaryAllOfAuthoritativeNameservers {\n");
            sb.Append("  Assigned: ").Append(Assigned).Append("\n");
            sb.Append("  Delegated: ").Append(Delegated).Append("\n");
            sb.Append("  DelegationLastCheck: ").Append(DelegationLastCheck).Append("\n");
            sb.Append("  DelegationStatus: ").Append(DelegationStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ZonePrimaryAllOfAuthoritativeNameservers" />
    /// </summary>
    public partial class ZonePrimaryAllOfAuthoritativeNameserversJsonConverter : JsonConverter<ZonePrimaryAllOfAuthoritativeNameservers>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ZonePrimaryAllOfAuthoritativeNameserversJsonConverter" /> class.
        /// </summary>
        public ZonePrimaryAllOfAuthoritativeNameserversJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize DelegationLastCheck
        /// </summary>
        public string DelegationLastCheckFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ZonePrimaryAllOfAuthoritativeNameservers" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ZonePrimaryAllOfAuthoritativeNameservers Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> assigned = default;
            Option<List<string>?> delegated = default;
            Option<DateTime?> delegationLastCheck = default;
            Option<ZonePrimaryAllOfAuthoritativeNameservers.DelegationStatusEnum?> delegationStatus = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "assigned":
                            assigned = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "delegated":
                            delegated = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "delegation_last_check":
                            delegationLastCheck = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "delegation_status":
                            string? delegationStatusRawValue = utf8JsonReader.GetString();
                            if (delegationStatusRawValue != null)
                                delegationStatus = new Option<ZonePrimaryAllOfAuthoritativeNameservers.DelegationStatusEnum?>(ZonePrimaryAllOfAuthoritativeNameservers.DelegationStatusEnumFromStringOrDefault(delegationStatusRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!assigned.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimaryAllOfAuthoritativeNameservers.", nameof(assigned));

            if (!delegated.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimaryAllOfAuthoritativeNameservers.", nameof(delegated));

            if (!delegationLastCheck.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimaryAllOfAuthoritativeNameservers.", nameof(delegationLastCheck));

            if (assigned.IsSet && assigned.Value == null)
                throw new ArgumentNullException(nameof(assigned), "Property is not nullable for class ZonePrimaryAllOfAuthoritativeNameservers.");

            if (delegated.IsSet && delegated.Value == null)
                throw new ArgumentNullException(nameof(delegated), "Property is not nullable for class ZonePrimaryAllOfAuthoritativeNameservers.");

            if (delegationStatus.IsSet && delegationStatus.Value == null)
                throw new ArgumentNullException(nameof(delegationStatus), "Property is not nullable for class ZonePrimaryAllOfAuthoritativeNameservers.");

            return new ZonePrimaryAllOfAuthoritativeNameservers(assigned.Value!, delegated.Value!, delegationLastCheck.Value!, delegationStatus);
        }

        /// <summary>
        /// Serializes a <see cref="ZonePrimaryAllOfAuthoritativeNameservers" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="zonePrimaryAllOfAuthoritativeNameservers"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ZonePrimaryAllOfAuthoritativeNameservers zonePrimaryAllOfAuthoritativeNameservers, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, zonePrimaryAllOfAuthoritativeNameservers, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ZonePrimaryAllOfAuthoritativeNameservers" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="zonePrimaryAllOfAuthoritativeNameservers"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ZonePrimaryAllOfAuthoritativeNameservers zonePrimaryAllOfAuthoritativeNameservers, JsonSerializerOptions jsonSerializerOptions)
        {
            if (zonePrimaryAllOfAuthoritativeNameservers.Assigned == null)
                throw new ArgumentNullException(nameof(zonePrimaryAllOfAuthoritativeNameservers.Assigned), "Property is required for class ZonePrimaryAllOfAuthoritativeNameservers.");

            if (zonePrimaryAllOfAuthoritativeNameservers.Delegated == null)
                throw new ArgumentNullException(nameof(zonePrimaryAllOfAuthoritativeNameservers.Delegated), "Property is required for class ZonePrimaryAllOfAuthoritativeNameservers.");

            writer.WritePropertyName("assigned");
            JsonSerializer.Serialize(writer, zonePrimaryAllOfAuthoritativeNameservers.Assigned, jsonSerializerOptions);
            writer.WritePropertyName("delegated");
            JsonSerializer.Serialize(writer, zonePrimaryAllOfAuthoritativeNameservers.Delegated, jsonSerializerOptions);
            if (zonePrimaryAllOfAuthoritativeNameservers.DelegationLastCheck != null)
                writer.WriteString("delegation_last_check", zonePrimaryAllOfAuthoritativeNameservers.DelegationLastCheck.Value.ToString(DelegationLastCheckFormat));
            else
                writer.WriteNull("delegation_last_check");

            var delegationStatusRawValue = ZonePrimaryAllOfAuthoritativeNameservers.DelegationStatusEnumToJsonValue(zonePrimaryAllOfAuthoritativeNameservers.DelegationStatusOption.Value!.Value);
            writer.WriteString("delegation_status", delegationStatusRawValue);
        }
    }
}
