// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * This is the .NET Library for the Hetzner Cloud API.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HCloudAPI.Clients;

namespace HCloudAPI.Model
{
    /// <summary>
    /// ZonePrimary
    /// </summary>
    public partial class ZonePrimary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ZonePrimary" /> class.
        /// </summary>
        /// <param name="id">ID of the [Zone](#tag/zones).</param>
        /// <param name="name">Name of the [Zone](#tag/zones).  All names with [well-known public suffixes](https://publicsuffix.org/) (e.g. &#x60;.de&#x60;, &#x60;.com&#x60;, &#x60;.co.uk&#x60;) are supported. Subdomains are not supported.  The name must be in lower case and must not end with a dot. [Internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) must be transcribed to [Punycode](https://wikipedia.org/wiki/Punycode) representation with ACE prefix, e.g. &#x60;xn- -mnchen-3ya.de&#x60; (&#x60;münchen.de&#x60;). </param>
        /// <param name="created">Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).</param>
        /// <param name="labels">User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#description/labels)\&quot;. </param>
        /// <param name="protection">protection</param>
        /// <param name="status">Status of the [Zone](#tag/zones). </param>
        /// <param name="recordCount">Number of resource records (RR) within the [Zone](#tag/zones).</param>
        /// <param name="authoritativeNameservers">authoritativeNameservers</param>
        /// <param name="registrar">Registrar of the domain.</param>
        /// <param name="mode">Mode of the [Zone](#tag/zones).  For more information, see [Zone Modes](#tag/zones/zone-modes). </param>
        /// <param name="primaryNameservers">Primary nameservers of the [Zone](#tag/zones).  Only set if [Zone](#tag/zones) is in [secondary mode](#tag/zones/zone-modes), otherwise empty. </param>
        /// <param name="ttl">Default Time To Live (TTL) of the [Zone](#tag/zones).  Must be in between 60s and 2147483647s.  This TTL is used for [RRSets](#tag/zone-rrsets) that do not explicitly define a TTL.  (default to 3600)</param>
        [JsonConstructor]
        public ZonePrimary(long id, string name, DateTime created, Dictionary<string, string> labels, ListFloatingIpsResponseFloatingIpsInnerProtection protection, StatusEnum status, int recordCount, ZonePrimaryAllOfAuthoritativeNameservers authoritativeNameservers, RegistrarEnum registrar, ModeEnum mode, Option<List<ZonePrimaryAllOfPrimaryNameservers>?> primaryNameservers = default, int ttl = 3600)
        {
            Id = id;
            Name = name;
            Created = created;
            Labels = labels;
            Protection = protection;
            Status = status;
            RecordCount = recordCount;
            AuthoritativeNameservers = authoritativeNameservers;
            Registrar = registrar;
            Mode = mode;
            PrimaryNameserversOption = primaryNameservers;
            Ttl = ttl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Status of the [Zone](#tag/zones). 
        /// </summary>
        /// <value>Status of the [Zone](#tag/zones). </value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Ok for value: ok
            /// </summary>
            Ok = 1,

            /// <summary>
            /// Enum Updating for value: updating
            /// </summary>
            Updating = 2,

            /// <summary>
            /// Enum Error for value: error
            /// </summary>
            Error = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("ok"))
                return StatusEnum.Ok;

            if (value.Equals("updating"))
                return StatusEnum.Updating;

            if (value.Equals("error"))
                return StatusEnum.Error;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ok"))
                return StatusEnum.Ok;

            if (value.Equals("updating"))
                return StatusEnum.Updating;

            if (value.Equals("error"))
                return StatusEnum.Error;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Ok)
                return "ok";

            if (value == StatusEnum.Updating)
                return "updating";

            if (value == StatusEnum.Error)
                return "error";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Status of the [Zone](#tag/zones). 
        /// </summary>
        /// <value>Status of the [Zone](#tag/zones). </value>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Registrar of the domain.
        /// </summary>
        /// <value>Registrar of the domain.</value>
        public enum RegistrarEnum
        {
            /// <summary>
            /// Enum Hetzner for value: hetzner
            /// </summary>
            Hetzner = 1,

            /// <summary>
            /// Enum Other for value: other
            /// </summary>
            Other = 2,

            /// <summary>
            /// Enum Unknown for value: unknown
            /// </summary>
            Unknown = 3
        }

        /// <summary>
        /// Returns a <see cref="RegistrarEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static RegistrarEnum RegistrarEnumFromString(string value)
        {
            if (value.Equals("hetzner"))
                return RegistrarEnum.Hetzner;

            if (value.Equals("other"))
                return RegistrarEnum.Other;

            if (value.Equals("unknown"))
                return RegistrarEnum.Unknown;

            throw new NotImplementedException($"Could not convert value to type RegistrarEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="RegistrarEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RegistrarEnum? RegistrarEnumFromStringOrDefault(string value)
        {
            if (value.Equals("hetzner"))
                return RegistrarEnum.Hetzner;

            if (value.Equals("other"))
                return RegistrarEnum.Other;

            if (value.Equals("unknown"))
                return RegistrarEnum.Unknown;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="RegistrarEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string RegistrarEnumToJsonValue(RegistrarEnum value)
        {
            if (value == RegistrarEnum.Hetzner)
                return "hetzner";

            if (value == RegistrarEnum.Other)
                return "other";

            if (value == RegistrarEnum.Unknown)
                return "unknown";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Registrar of the domain.
        /// </summary>
        /// <value>Registrar of the domain.</value>
        [JsonPropertyName("registrar")]
        public RegistrarEnum Registrar { get; set; }

        /// <summary>
        /// Mode of the [Zone](#tag/zones).  For more information, see [Zone Modes](#tag/zones/zone-modes). 
        /// </summary>
        /// <value>Mode of the [Zone](#tag/zones).  For more information, see [Zone Modes](#tag/zones/zone-modes). </value>
        public enum ModeEnum
        {
            /// <summary>
            /// Enum Primary for value: primary
            /// </summary>
            Primary = 1
        }

        /// <summary>
        /// Returns a <see cref="ModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ModeEnum ModeEnumFromString(string value)
        {
            if (value.Equals("primary"))
                return ModeEnum.Primary;

            throw new NotImplementedException($"Could not convert value to type ModeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ModeEnum? ModeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("primary"))
                return ModeEnum.Primary;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ModeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ModeEnumToJsonValue(ModeEnum value)
        {
            if (value == ModeEnum.Primary)
                return "primary";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Mode of the [Zone](#tag/zones).  For more information, see [Zone Modes](#tag/zones/zone-modes). 
        /// </summary>
        /// <value>Mode of the [Zone](#tag/zones).  For more information, see [Zone Modes](#tag/zones/zone-modes). </value>
        /* <example>primary</example> */
        [JsonPropertyName("mode")]
        public ModeEnum Mode { get; set; }

        /// <summary>
        /// ID of the [Zone](#tag/zones).
        /// </summary>
        /// <value>ID of the [Zone](#tag/zones).</value>
        /* <example>42</example> */
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Name of the [Zone](#tag/zones).  All names with [well-known public suffixes](https://publicsuffix.org/) (e.g. &#x60;.de&#x60;, &#x60;.com&#x60;, &#x60;.co.uk&#x60;) are supported. Subdomains are not supported.  The name must be in lower case and must not end with a dot. [Internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) must be transcribed to [Punycode](https://wikipedia.org/wiki/Punycode) representation with ACE prefix, e.g. &#x60;xn- -mnchen-3ya.de&#x60; (&#x60;münchen.de&#x60;). 
        /// </summary>
        /// <value>Name of the [Zone](#tag/zones).  All names with [well-known public suffixes](https://publicsuffix.org/) (e.g. &#x60;.de&#x60;, &#x60;.com&#x60;, &#x60;.co.uk&#x60;) are supported. Subdomains are not supported.  The name must be in lower case and must not end with a dot. [Internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) must be transcribed to [Punycode](https://wikipedia.org/wiki/Punycode) representation with ACE prefix, e.g. &#x60;xn- -mnchen-3ya.de&#x60; (&#x60;münchen.de&#x60;). </value>
        /* <example>example.com</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
        /// </summary>
        /// <value>Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).</value>
        /* <example>2016-01-30T23:55:00Z</example> */
        [JsonPropertyName("created")]
        public DateTime Created { get; set; }

        /// <summary>
        /// User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#description/labels)\&quot;. 
        /// </summary>
        /// <value>User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#description/labels)\&quot;. </value>
        /* <example>{environment&#x3D;prod, example.com/my&#x3D;label, just-a-key&#x3D;}</example> */
        [JsonPropertyName("labels")]
        public Dictionary<string, string> Labels { get; set; }

        /// <summary>
        /// Gets or Sets Protection
        /// </summary>
        [JsonPropertyName("protection")]
        public ListFloatingIpsResponseFloatingIpsInnerProtection Protection { get; set; }

        /// <summary>
        /// Number of resource records (RR) within the [Zone](#tag/zones).
        /// </summary>
        /// <value>Number of resource records (RR) within the [Zone](#tag/zones).</value>
        [JsonPropertyName("record_count")]
        public int RecordCount { get; set; }

        /// <summary>
        /// Gets or Sets AuthoritativeNameservers
        /// </summary>
        [JsonPropertyName("authoritative_nameservers")]
        public ZonePrimaryAllOfAuthoritativeNameservers AuthoritativeNameservers { get; set; }

        /// <summary>
        /// Used to track the state of PrimaryNameservers
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ZonePrimaryAllOfPrimaryNameservers>?> PrimaryNameserversOption { get; private set; }

        /// <summary>
        /// Primary nameservers of the [Zone](#tag/zones).  Only set if [Zone](#tag/zones) is in [secondary mode](#tag/zones/zone-modes), otherwise empty. 
        /// </summary>
        /// <value>Primary nameservers of the [Zone](#tag/zones).  Only set if [Zone](#tag/zones) is in [secondary mode](#tag/zones/zone-modes), otherwise empty. </value>
        /* <example>[{&quot;address&quot;:&quot;198.51.100.1&quot;,&quot;port&quot;:53},{&quot;address&quot;:&quot;203.0.113.1&quot;,&quot;port&quot;:53}]</example> */
        [JsonPropertyName("primary_nameservers")]
        public List<ZonePrimaryAllOfPrimaryNameservers>? PrimaryNameservers { get { return this.PrimaryNameserversOption.Value; } set { this.PrimaryNameserversOption = new(value); } }

        /// <summary>
        /// Default Time To Live (TTL) of the [Zone](#tag/zones).  Must be in between 60s and 2147483647s.  This TTL is used for [RRSets](#tag/zone-rrsets) that do not explicitly define a TTL. 
        /// </summary>
        /// <value>Default Time To Live (TTL) of the [Zone](#tag/zones).  Must be in between 60s and 2147483647s.  This TTL is used for [RRSets](#tag/zone-rrsets) that do not explicitly define a TTL. </value>
        /* <example>10800</example> */
        [JsonPropertyName("ttl")]
        public int Ttl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ZonePrimary {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  Protection: ").Append(Protection).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  RecordCount: ").Append(RecordCount).Append("\n");
            sb.Append("  AuthoritativeNameservers: ").Append(AuthoritativeNameservers).Append("\n");
            sb.Append("  Registrar: ").Append(Registrar).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  PrimaryNameservers: ").Append(PrimaryNameservers).Append("\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (long) maximum
            if (this.Id > (long)9007199254740991)
            {
                yield return new ValidationResult("Invalid value for Id, must be a value less than or equal to 9007199254740991.", new [] { "Id" });
            }

            // Id (long) minimum
            if (this.Id < (long)1)
            {
                yield return new ValidationResult("Invalid value for Id, must be a value greater than or equal to 1.", new [] { "Id" });
            }

            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 255.", new [] { "Name" });
            }

            // Ttl (int) maximum
            if (this.Ttl > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for Ttl, must be a value less than or equal to 2147483647.", new [] { "Ttl" });
            }

            // Ttl (int) minimum
            if (this.Ttl < (int)60)
            {
                yield return new ValidationResult("Invalid value for Ttl, must be a value greater than or equal to 60.", new [] { "Ttl" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ZonePrimary" />
    /// </summary>
    public partial class ZonePrimaryJsonConverter : JsonConverter<ZonePrimary>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ZonePrimaryJsonConverter" /> class.
        /// </summary>
        public ZonePrimaryJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize Created
        /// </summary>
        public string CreatedFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ZonePrimary" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ZonePrimary Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<string?> name = default;
            Option<DateTime?> created = default;
            Option<Dictionary<string, string>?> labels = default;
            Option<ListFloatingIpsResponseFloatingIpsInnerProtection?> protection = default;
            Option<ZonePrimary.StatusEnum?> status = default;
            Option<int?> recordCount = default;
            Option<ZonePrimaryAllOfAuthoritativeNameservers?> authoritativeNameservers = default;
            Option<ZonePrimary.RegistrarEnum?> registrar = default;
            Option<ZonePrimary.ModeEnum?> mode = default;
            Option<List<ZonePrimaryAllOfPrimaryNameservers>?> primaryNameservers = default;
            Option<int?> ttl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created":
                            created = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "labels":
                            labels = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "protection":
                            protection = new Option<ListFloatingIpsResponseFloatingIpsInnerProtection?>(JsonSerializer.Deserialize<ListFloatingIpsResponseFloatingIpsInnerProtection>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<ZonePrimary.StatusEnum?>(ZonePrimary.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "record_count":
                            recordCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "authoritative_nameservers":
                            authoritativeNameservers = new Option<ZonePrimaryAllOfAuthoritativeNameservers?>(JsonSerializer.Deserialize<ZonePrimaryAllOfAuthoritativeNameservers>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "registrar":
                            string? registrarRawValue = utf8JsonReader.GetString();
                            if (registrarRawValue != null)
                                registrar = new Option<ZonePrimary.RegistrarEnum?>(ZonePrimary.RegistrarEnumFromStringOrDefault(registrarRawValue));
                            break;
                        case "mode":
                            string? modeRawValue = utf8JsonReader.GetString();
                            if (modeRawValue != null)
                                mode = new Option<ZonePrimary.ModeEnum?>(ZonePrimary.ModeEnumFromStringOrDefault(modeRawValue));
                            break;
                        case "primary_nameservers":
                            primaryNameservers = new Option<List<ZonePrimaryAllOfPrimaryNameservers>?>(JsonSerializer.Deserialize<List<ZonePrimaryAllOfPrimaryNameservers>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "ttl":
                            ttl = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(name));

            if (!created.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(created));

            if (!labels.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(labels));

            if (!protection.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(protection));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(status));

            if (!recordCount.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(recordCount));

            if (!authoritativeNameservers.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(authoritativeNameservers));

            if (!registrar.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(registrar));

            if (!mode.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(mode));

            if (!ttl.IsSet)
                throw new ArgumentException("Property is required for class ZonePrimary.", nameof(ttl));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ZonePrimary.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ZonePrimary.");

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class ZonePrimary.");

            if (labels.IsSet && labels.Value == null)
                throw new ArgumentNullException(nameof(labels), "Property is not nullable for class ZonePrimary.");

            if (protection.IsSet && protection.Value == null)
                throw new ArgumentNullException(nameof(protection), "Property is not nullable for class ZonePrimary.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class ZonePrimary.");

            if (recordCount.IsSet && recordCount.Value == null)
                throw new ArgumentNullException(nameof(recordCount), "Property is not nullable for class ZonePrimary.");

            if (authoritativeNameservers.IsSet && authoritativeNameservers.Value == null)
                throw new ArgumentNullException(nameof(authoritativeNameservers), "Property is not nullable for class ZonePrimary.");

            if (registrar.IsSet && registrar.Value == null)
                throw new ArgumentNullException(nameof(registrar), "Property is not nullable for class ZonePrimary.");

            if (mode.IsSet && mode.Value == null)
                throw new ArgumentNullException(nameof(mode), "Property is not nullable for class ZonePrimary.");

            if (primaryNameservers.IsSet && primaryNameservers.Value == null)
                throw new ArgumentNullException(nameof(primaryNameservers), "Property is not nullable for class ZonePrimary.");

            if (ttl.IsSet && ttl.Value == null)
                throw new ArgumentNullException(nameof(ttl), "Property is not nullable for class ZonePrimary.");

            return new ZonePrimary(id.Value!.Value!, name.Value!, created.Value!.Value!, labels.Value!, protection.Value!, status.Value!.Value!, recordCount.Value!.Value!, authoritativeNameservers.Value!, registrar.Value!.Value!, mode.Value!.Value!, primaryNameservers, ttl.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ZonePrimary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="zonePrimary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ZonePrimary zonePrimary, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, zonePrimary, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ZonePrimary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="zonePrimary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ZonePrimary zonePrimary, JsonSerializerOptions jsonSerializerOptions)
        {
            if (zonePrimary.Name == null)
                throw new ArgumentNullException(nameof(zonePrimary.Name), "Property is required for class ZonePrimary.");

            if (zonePrimary.Labels == null)
                throw new ArgumentNullException(nameof(zonePrimary.Labels), "Property is required for class ZonePrimary.");

            if (zonePrimary.Protection == null)
                throw new ArgumentNullException(nameof(zonePrimary.Protection), "Property is required for class ZonePrimary.");

            if (zonePrimary.AuthoritativeNameservers == null)
                throw new ArgumentNullException(nameof(zonePrimary.AuthoritativeNameservers), "Property is required for class ZonePrimary.");

            if (zonePrimary.PrimaryNameserversOption.IsSet && zonePrimary.PrimaryNameservers == null)
                throw new ArgumentNullException(nameof(zonePrimary.PrimaryNameservers), "Property is required for class ZonePrimary.");

            writer.WriteNumber("id", zonePrimary.Id);

            writer.WriteString("name", zonePrimary.Name);

            writer.WriteString("created", zonePrimary.Created.ToString(CreatedFormat));

            writer.WritePropertyName("labels");
            JsonSerializer.Serialize(writer, zonePrimary.Labels, jsonSerializerOptions);
            writer.WritePropertyName("protection");
            JsonSerializer.Serialize(writer, zonePrimary.Protection, jsonSerializerOptions);
            var statusRawValue = ZonePrimary.StatusEnumToJsonValue(zonePrimary.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteNumber("record_count", zonePrimary.RecordCount);

            writer.WritePropertyName("authoritative_nameservers");
            JsonSerializer.Serialize(writer, zonePrimary.AuthoritativeNameservers, jsonSerializerOptions);
            var registrarRawValue = ZonePrimary.RegistrarEnumToJsonValue(zonePrimary.Registrar);
            writer.WriteString("registrar", registrarRawValue);
            var modeRawValue = ZonePrimary.ModeEnumToJsonValue(zonePrimary.Mode);
            writer.WriteString("mode", modeRawValue);
            if (zonePrimary.PrimaryNameserversOption.IsSet)
            {
                writer.WritePropertyName("primary_nameservers");
                JsonSerializer.Serialize(writer, zonePrimary.PrimaryNameservers, jsonSerializerOptions);
            }
            writer.WriteNumber("ttl", zonePrimary.Ttl);
        }
    }
}
