name: .NET

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:  
      matrix:
        dotnet-version: [ '5.0.x', '6.0.x', '7.0.x', '8.0.x', '9.0.x', '10.0.x' ]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' 
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Pack NuGet Package
      run: dotnet pack --configuration Release --output ./artifacts
      
    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
        
    - name: NuGet push
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

    - name: add dotnet source github
      run: dotnet nuget add source --username Skorplul --password ${{ secrets.PACKAGES_KEY }} --name github "https://nuget.pkg.github.com/Skorplul/index.json"

    - name: push github
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.PACKAGES_KEY }} --source "github"
